#!/usr/bin/env bash
set -euo pipefail

# Test: scripts/generate-agents-md.sh (DF-6 — the script previously
# concatenated full reference-file bodies verbatim and produced 337/284
# line AGENTS.md files on real repos, blowing through its documented
# 60-120 line budget). Fixtures live in mktemp dirs; the script is invoked
# via its real path in this repo but with CWD set to the fixture, so
# generation only ever sees the fixture's own files.
#
# Covers:
#   (a) bulky reference set (real dotnet stack files + 15 synthetic extra
#       supplements) -> output stays <= 120 lines (soft budget) and the
#       auto-generated marker is present
#   (b) a fixture so bulky even after dropping every droppable section it
#       would exceed the hard ceiling -> output never exceeds 140 lines,
#       and the budget comment is the last line
#   (c) `## Custom:` sections are preserved verbatim across regeneration
#   (d) never inlines a full reference-file body (a distinctive marker
#       string deep in a reference file's body must NOT appear in the
#       generated AGENTS.md; only the heading/pointer summary should)
#   (e) existing contracts unchanged: marker-refusal guard falls back to
#       AGENTS.generated.md, and --force overwrites a hand-curated file

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
GEN="$REPO_ROOT/scripts/generate-agents-md.sh"

echo "=== generate-agents-md.sh Test (DF-6) ==="
[ -f "$GEN" ] || { echo "  FAIL  script not found: $GEN" >&2; exit 1; }
[ -x "$GEN" ] || { echo "  FAIL  script not executable: $GEN" >&2; exit 1; }

declare -a FAILS=()
TMPDIR_FIXTURES="$(mktemp -d)"
cleanup() { rm -rf "$TMPDIR_FIXTURES"; }
trap cleanup EXIT

# --- (a) bulky reference set -> <= 120 lines, marker present -----------------
FIXTURE_A="$TMPDIR_FIXTURES/a-bulky"
mkdir -p "$FIXTURE_A/.claude/references/dotnet"
echo "dotnet" > "$FIXTURE_A/.claude/tech-stack"
cp "$REPO_ROOT/.claude/references/security-checklist.md" \
   "$REPO_ROOT/.claude/references/testing-patterns.md" \
   "$REPO_ROOT/.claude/references/performance-checklist.md" \
   "$REPO_ROOT/.claude/references/domain-finance.md" \
   "$FIXTURE_A/.claude/references/"
cp "$REPO_ROOT/.claude/references/dotnet/"*.md "$FIXTURE_A/.claude/references/dotnet/"
cat > "$FIXTURE_A/.claude/references/architecture-principles.md" <<'EOF'
---
description: Auto-generated architecture map of this repo's layering and dependency rules
---
# Architecture Principles

Intro line describing the layering approach used across this codebase.

## Layering
## Dependency Rules
## Module Boundaries
EOF
for i in $(seq 1 15); do
  cat > "$FIXTURE_A/.claude/references/dotnet/extra-supplement-$i.md" <<EOF
---
description: Extra bulky supplement number $i for load testing the AGENTS.md budget
---
# Extra Supplement $i

Some intro text repeated to bulk out the fixture body so the naive
full-body-concatenation strategy this test guards against would blow
well past the 120-line budget on its own.

## Section A $i
## Section B $i
## Section C $i
EOF
done
cat > "$FIXTURE_A/CLAUDE.md" <<'EOF'
# Project

## Critical Rules (Always Apply)

- **C0.1** rule one
- **C0.2** rule two
EOF

echo ""; echo "--- (a) bulky reference set: output <= 120 lines, marker present ---"
out_a="$(cd "$FIXTURE_A" && bash "$GEN" 2>&1)"
lines_a="$(wc -l < "$FIXTURE_A/AGENTS.md" | tr -d ' ')"
if [ "$lines_a" -le 120 ] && grep -qF "Auto-generated by MTK" "$FIXTURE_A/AGENTS.md"; then
  echo "  PASS  $lines_a lines (<= 120), marker present"
else
  FAILS+=("(a) expected <= 120 lines with marker, got $lines_a lines. Script output: $out_a")
fi

# --- (b) hard ceiling: never emit more than 140 lines -----------------------
FIXTURE_B="$TMPDIR_FIXTURES/b-hard-ceiling"
mkdir -p "$FIXTURE_B"
{
  echo "# Project"
  echo ""
  echo "## Critical Rules (Always Apply)"
  echo ""
  for i in $(seq 1 200); do
    echo "- **C0.$i** rule number $i with some extra padding text to pad it out"
  done
} > "$FIXTURE_B/CLAUDE.md"

echo ""; echo "--- (b) oversized non-droppable content: output <= 140 lines (hard ceiling) ---"
out_b="$(cd "$FIXTURE_B" && bash "$GEN" 2>&1)"
lines_b="$(wc -l < "$FIXTURE_B/AGENTS.md" | tr -d ' ')"
last_line_b="$(tail -1 "$FIXTURE_B/AGENTS.md")"
if [ "$lines_b" -le 140 ] && printf '%s' "$last_line_b" | grep -q "sections summarized to fit"; then
  echo "  PASS  $lines_b lines (<= 140 hard ceiling), budget comment is the last line"
else
  FAILS+=("(b) expected <= 140 lines ending in the budget comment, got $lines_b lines, last line: $last_line_b. Script output: $out_b")
fi

# --- (c) Custom sections preserved across regeneration ----------------------
FIXTURE_C="$TMPDIR_FIXTURES/c-custom-preserved"
mkdir -p "$FIXTURE_C"
cat > "$FIXTURE_C/CLAUDE.md" <<'EOF'
# Project

## Critical Rules (Always Apply)

- **C0.1** rule one
EOF

echo ""; echo "--- (c) Custom sections preserved across regeneration ---"
(cd "$FIXTURE_C" && bash "$GEN" >/dev/null 2>&1)
cat >> "$FIXTURE_C/AGENTS.md" <<'EOF'

## Custom: Team Notes

- Our team always does X.
EOF
(cd "$FIXTURE_C" && bash "$GEN" >/dev/null 2>&1)
if grep -q "^## Custom: Team Notes" "$FIXTURE_C/AGENTS.md" && grep -qF "Our team always does X." "$FIXTURE_C/AGENTS.md"; then
  echo "  PASS  Custom: Team Notes section survives regeneration"
else
  FAILS+=("(c) expected '## Custom: Team Notes' and its body to survive regeneration, got: $(cat "$FIXTURE_C/AGENTS.md")")
fi

# --- (d) never inlines a full reference-file body ---------------------------
FIXTURE_D="$TMPDIR_FIXTURES/d-no-full-body"
mkdir -p "$FIXTURE_D/.claude/references"
cat > "$FIXTURE_D/.claude/references/security-checklist.md" <<'EOF'
---
description: Baseline security checklist for any serious software change
---
# Security Checklist

Fast security and compliance reference for serious software.

## Input And Auth

- UNIQUE_DEEP_BODY_MARKER_ZQX9 this sentence must never appear verbatim in AGENTS.md
EOF
cat > "$FIXTURE_D/CLAUDE.md" <<'EOF'
# Project

## Critical Rules (Always Apply)

- **C0.1** rule one
EOF

echo ""; echo "--- (d) full reference body is never inlined (headings/pointer only) ---"
(cd "$FIXTURE_D" && bash "$GEN" >/dev/null 2>&1)
if grep -q "UNIQUE_DEEP_BODY_MARKER_ZQX9" "$FIXTURE_D/AGENTS.md"; then
  FAILS+=("(d) full reference-file body leaked into AGENTS.md — deep body marker found verbatim")
elif grep -q "See \`.claude/references/security-checklist.md\`" "$FIXTURE_D/AGENTS.md"; then
  echo "  PASS  body not inlined; pointer to the source file present instead"
else
  FAILS+=("(d) expected a 'See \`.claude/references/security-checklist.md\`' pointer, got: $(cat "$FIXTURE_D/AGENTS.md")")
fi

# --- (e) existing contracts: marker-refusal guard + --force -----------------
FIXTURE_E="$TMPDIR_FIXTURES/e-existing-contracts"
mkdir -p "$FIXTURE_E"
cat > "$FIXTURE_E/CLAUDE.md" <<'EOF'
# Project

## Critical Rules (Always Apply)

- **C0.1** rule one
EOF
echo "# Hand-curated AGENTS.md, no marker here" > "$FIXTURE_E/AGENTS.md"

echo ""; echo "--- (e) marker-refusal guard falls back to AGENTS.generated.md ---"
(cd "$FIXTURE_E" && bash "$GEN" >/dev/null 2>&1) || true
if [ -f "$FIXTURE_E/AGENTS.generated.md" ] && grep -q "^# Hand-curated AGENTS.md" "$FIXTURE_E/AGENTS.md"; then
  echo "  PASS  hand-curated AGENTS.md untouched, fallback written to AGENTS.generated.md"
else
  FAILS+=("(e) expected AGENTS.md untouched and AGENTS.generated.md created")
fi

echo ""; echo "--- (e) --force overwrites the hand-curated file ---"
(cd "$FIXTURE_E" && bash "$GEN" --force >/dev/null 2>&1)
if grep -qF "Auto-generated by MTK" "$FIXTURE_E/AGENTS.md"; then
  echo "  PASS  --force overwrote AGENTS.md with the generated marker"
else
  FAILS+=("(e) expected --force to overwrite AGENTS.md with the generated marker")
fi

echo ""
if [ ${#FAILS[@]} -gt 0 ]; then
  printf '  FAIL  %s\n' "${FAILS[@]}" >&2
  exit 1
fi
echo "========================================"
echo "TEST PASSED — all DF-6 generate-agents-md.sh assertions green"
