#!/usr/bin/env bash
set -euo pipefail

# validate-handoff.sh — derived artifacts are collateral, not undeclared drift.
#
# WHY. A 2026-09 field run spent a drift slot on `.claude/rules/INDEX.md`: a file
# regenerated by a script, whose own header says so, reported as CRITICAL drift
# because the planner's change_manifest had not enumerated machine output.
# Hand-written files outside the manifest must still be critical.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
VH="$REPO_ROOT/scripts/validate-handoff.sh"

fail() { printf 'FAIL: %s\n' "$1" >&2; exit 1; }
ok()   { printf 'PASS: %s\n' "$1"; }

PROJ="$(mktemp -d -t mtk-vhd-XXXXXX)"
trap 'rm -rf "$PROJ"' EXIT

cd "$PROJ"
git init -q .
git config user.email t@example.com
git config user.name t
mkdir -p src docs/specs gen
printf 'base\n' > README.md
git add -A && git commit -qm base
BASE="$(git rev-parse HEAD)"

cat > docs/specs/2026-09-18-derived.json <<'JSON'
{
  "slug": "derived",
  "security_impact": "none",
  "change_manifest": [
    { "path": "src/Handler.cs", "action": "modify", "purpose": "the actual change" }
  ]
}
JSON

printf 'class Handler {}\n' > src/Handler.cs

# Three shapes of machine output: a lockfile by name, a generated source file by
# extension, and an ordinary-looking markdown file that declares itself in its header.
printf '{"lockfileVersion":3}\n' > package-lock.json
printf '// <auto-generated />\npublic partial class Ctx {}\n' > gen/Model.Designer.cs
printf '# Index\n\n> GENERATED by scripts/build-index.sh -- do not edit by hand.\n\n| a |\n' > gen/INDEX.md

out="$(bash "$VH" docs/specs/2026-09-18-derived.json "$BASE" || true)"

grep -q '## NOTE: derived artifacts touched but not declared' <<<"$out" \
  || fail "no derived-artifact note emitted:\n$out"
for f in package-lock.json gen/Model.Designer.cs gen/INDEX.md; do
  grep -q -- "- \`$f\`" <<<"$(sed -n '/NOTE: derived/,/^## /p' <<<"$out")" \
    || fail "$f not classified as derived:\n$out"
done
grep -q '## CRITICAL: files touched but NOT in change_manifest' <<<"$out" \
  && fail "derived files alone must not raise critical drift:\n$out"
grep -q '## PASS' <<<"$out" || fail "expected PASS with only derived collateral:\n$out"
ok "lockfile, generated source, and self-declaring file report as collateral, not drift"

# A hand-written file outside the manifest is still critical.
printf 'class Rogue {}\n' > src/Rogue.cs
out2="$(bash "$VH" docs/specs/2026-09-18-derived.json "$BASE" || true)"
grep -q '## CRITICAL: files touched but NOT in change_manifest' <<<"$out2" \
  || fail "hand-written undeclared file must stay critical:\n$out2"
grep -q -- '- `src/Rogue.cs`' <<<"$out2" || fail "src/Rogue.cs missing from critical list:\n$out2"
sed -n '/CRITICAL: files touched/,/^## /p' <<<"$out2" | grep -q 'package-lock.json' \
  && fail "derived file leaked into the critical list:\n$out2"
ok "hand-written undeclared file still reports as critical drift"

printf '\nAll validate-handoff derived-artifact tests passed.\n'
