#!/usr/bin/env bash
set -euo pipefail

# Test: scripts/generate-agents-md.sh (DF-6 — the script previously
# concatenated full reference-file bodies verbatim and produced 337/284
# line AGENTS.md files on real repos, blowing through its documented
# 60-120 line budget). Fixtures live in mktemp dirs; the script is invoked
# via its real path in this repo but with CWD set to the fixture, so
# generation only ever sees the fixture's own files.
#
# Covers:
#   (a) bulky reference set (real dotnet stack files + 15 synthetic extra
#       supplements) -> output stays <= 120 lines (soft budget) and the
#       auto-generated marker is present
#   (b) a fixture so bulky even after dropping every droppable section it
#       would exceed the hard ceiling -> output never exceeds 140 lines,
#       and the budget comment is the last line
#   (c) `## Custom:` sections are preserved verbatim across regeneration
#   (d) never inlines a full reference-file body (a distinctive marker
#       string deep in a reference file's body must NOT appear in the
#       generated AGENTS.md; only the heading/pointer summary should)
#   (e) existing contracts unchanged: marker-refusal guard falls back to
#       AGENTS.generated.md, and --force overwrites a hand-curated file
#   (f) constitution resolution: when CLAUDE.md is a shim importing AGENTS.md
#       (`^@AGENTS\.md` line), the script prints a note and exits 0 without
#       writing anything (no regeneration, no AGENTS.generated.md fallback);
#       --force does NOT override that — it exits 1 and leaves the canonical
#       AGENTS.md byte-identical
#   (g) a GENERATOR-MARKED AGENTS.md is this script's own prior summary, never
#       canonical: a bare run and --force both regenerate it even beside a
#       CLAUDE.md shim, and the Critical Rules heading names CLAUDE.md
#   (h) an explicit non-default output path is honoured even when AGENTS.md is
#       canonical (the decline note must not advertise an inert option), while
#       an explicit `AGENTS.md` target keeps the decline/refusal

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
GEN="$REPO_ROOT/scripts/generate-agents-md.sh"

echo "=== generate-agents-md.sh Test (DF-6) ==="
[ -f "$GEN" ] || { echo "  FAIL  script not found: $GEN" >&2; exit 1; }
[ -x "$GEN" ] || { echo "  FAIL  script not executable: $GEN" >&2; exit 1; }

declare -a FAILS=()
TMPDIR_FIXTURES="$(mktemp -d)"
cleanup() { rm -rf "$TMPDIR_FIXTURES"; }
trap cleanup EXIT

# --- (a) bulky reference set -> <= 120 lines, marker present -----------------
FIXTURE_A="$TMPDIR_FIXTURES/a-bulky"
mkdir -p "$FIXTURE_A/.claude/references/dotnet"
echo "dotnet" > "$FIXTURE_A/.claude/tech-stack"
cp "$REPO_ROOT/.claude/references/security-checklist.md" \
   "$REPO_ROOT/.claude/references/testing-patterns.md" \
   "$REPO_ROOT/.claude/references/performance-checklist.md" \
   "$REPO_ROOT/.claude/references/domain-finance.md" \
   "$FIXTURE_A/.claude/references/"
cp "$REPO_ROOT/.claude/references/dotnet/"*.md "$FIXTURE_A/.claude/references/dotnet/"
cat > "$FIXTURE_A/.claude/references/architecture-principles.md" <<'EOF'
---
description: Auto-generated architecture map of this repo's layering and dependency rules
---
# Architecture Principles

Intro line describing the layering approach used across this codebase.

## Layering
## Dependency Rules
## Module Boundaries
EOF
for i in $(seq 1 15); do
  cat > "$FIXTURE_A/.claude/references/dotnet/extra-supplement-$i.md" <<EOF
---
description: Extra bulky supplement number $i for load testing the AGENTS.md budget
---
# Extra Supplement $i

Some intro text repeated to bulk out the fixture body so the naive
full-body-concatenation strategy this test guards against would blow
well past the 120-line budget on its own.

## Section A $i
## Section B $i
## Section C $i
EOF
done
cat > "$FIXTURE_A/CLAUDE.md" <<'EOF'
# Project

## Critical Rules (Always Apply)

- **C0.1** rule one
- **C0.2** rule two
EOF

echo ""; echo "--- (a) bulky reference set: output <= 120 lines, marker present ---"
out_a="$(cd "$FIXTURE_A" && bash "$GEN" 2>&1)"
lines_a="$(wc -l < "$FIXTURE_A/AGENTS.md" | tr -d ' ')"
if [ "$lines_a" -le 120 ] && grep -qF "Auto-generated by MTK" "$FIXTURE_A/AGENTS.md"; then
  echo "  PASS  $lines_a lines (<= 120), marker present"
else
  FAILS+=("(a) expected <= 120 lines with marker, got $lines_a lines. Script output: $out_a")
fi

# --- (b) hard ceiling: never emit more than 140 lines -----------------------
FIXTURE_B="$TMPDIR_FIXTURES/b-hard-ceiling"
mkdir -p "$FIXTURE_B"
{
  echo "# Project"
  echo ""
  echo "## Critical Rules (Always Apply)"
  echo ""
  for i in $(seq 1 200); do
    echo "- **C0.$i** rule number $i with some extra padding text to pad it out"
  done
} > "$FIXTURE_B/CLAUDE.md"

echo ""; echo "--- (b) oversized non-droppable content: output <= 140 lines (hard ceiling) ---"
out_b="$(cd "$FIXTURE_B" && bash "$GEN" 2>&1)"
lines_b="$(wc -l < "$FIXTURE_B/AGENTS.md" | tr -d ' ')"
last_line_b="$(tail -1 "$FIXTURE_B/AGENTS.md")"
if [ "$lines_b" -le 140 ] && printf '%s' "$last_line_b" | grep -q "sections summarized to fit"; then
  echo "  PASS  $lines_b lines (<= 140 hard ceiling), budget comment is the last line"
else
  FAILS+=("(b) expected <= 140 lines ending in the budget comment, got $lines_b lines, last line: $last_line_b. Script output: $out_b")
fi

# --- (c) Custom sections preserved across regeneration ----------------------
FIXTURE_C="$TMPDIR_FIXTURES/c-custom-preserved"
mkdir -p "$FIXTURE_C"
cat > "$FIXTURE_C/CLAUDE.md" <<'EOF'
# Project

## Critical Rules (Always Apply)

- **C0.1** rule one
EOF

echo ""; echo "--- (c) Custom sections preserved across regeneration ---"
(cd "$FIXTURE_C" && bash "$GEN" >/dev/null 2>&1)
cat >> "$FIXTURE_C/AGENTS.md" <<'EOF'

## Custom: Team Notes

- Our team always does X.
EOF
(cd "$FIXTURE_C" && bash "$GEN" >/dev/null 2>&1)
if grep -q "^## Custom: Team Notes" "$FIXTURE_C/AGENTS.md" && grep -qF "Our team always does X." "$FIXTURE_C/AGENTS.md"; then
  echo "  PASS  Custom: Team Notes section survives regeneration"
else
  FAILS+=("(c) expected '## Custom: Team Notes' and its body to survive regeneration, got: $(cat "$FIXTURE_C/AGENTS.md")")
fi

# --- (d) never inlines a full reference-file body ---------------------------
FIXTURE_D="$TMPDIR_FIXTURES/d-no-full-body"
mkdir -p "$FIXTURE_D/.claude/references"
cat > "$FIXTURE_D/.claude/references/security-checklist.md" <<'EOF'
---
description: Baseline security checklist for any serious software change
---
# Security Checklist

Fast security and compliance reference for serious software.

## Input And Auth

- UNIQUE_DEEP_BODY_MARKER_ZQX9 this sentence must never appear verbatim in AGENTS.md
EOF
cat > "$FIXTURE_D/CLAUDE.md" <<'EOF'
# Project

## Critical Rules (Always Apply)

- **C0.1** rule one
EOF

echo ""; echo "--- (d) full reference body is never inlined (headings/pointer only) ---"
(cd "$FIXTURE_D" && bash "$GEN" >/dev/null 2>&1)
if grep -q "UNIQUE_DEEP_BODY_MARKER_ZQX9" "$FIXTURE_D/AGENTS.md"; then
  FAILS+=("(d) full reference-file body leaked into AGENTS.md — deep body marker found verbatim")
elif grep -q "See \`.claude/references/security-checklist.md\`" "$FIXTURE_D/AGENTS.md"; then
  echo "  PASS  body not inlined; pointer to the source file present instead"
else
  FAILS+=("(d) expected a 'See \`.claude/references/security-checklist.md\`' pointer, got: $(cat "$FIXTURE_D/AGENTS.md")")
fi

# --- (e) existing contracts: marker-refusal guard + --force -----------------
FIXTURE_E="$TMPDIR_FIXTURES/e-existing-contracts"
mkdir -p "$FIXTURE_E"
cat > "$FIXTURE_E/CLAUDE.md" <<'EOF'
# Project

## Critical Rules (Always Apply)

- **C0.1** rule one
EOF
echo "# Hand-curated AGENTS.md, no marker here" > "$FIXTURE_E/AGENTS.md"

echo ""; echo "--- (e) marker-refusal guard falls back to AGENTS.generated.md ---"
(cd "$FIXTURE_E" && bash "$GEN" >/dev/null 2>&1) || true
if [ -f "$FIXTURE_E/AGENTS.generated.md" ] && grep -q "^# Hand-curated AGENTS.md" "$FIXTURE_E/AGENTS.md"; then
  echo "  PASS  hand-curated AGENTS.md untouched, fallback written to AGENTS.generated.md"
else
  FAILS+=("(e) expected AGENTS.md untouched and AGENTS.generated.md created")
fi

echo ""; echo "--- (e) --force overwrites the hand-curated file ---"
(cd "$FIXTURE_E" && bash "$GEN" --force >/dev/null 2>&1)
if grep -qF "Auto-generated by MTK" "$FIXTURE_E/AGENTS.md"; then
  echo "  PASS  --force overwrote AGENTS.md with the generated marker"
else
  FAILS+=("(e) expected --force to overwrite AGENTS.md with the generated marker")
fi

# --- (f) constitution resolution: CLAUDE.md shim -> note, no write, exit 0 --
FIXTURE_F="$TMPDIR_FIXTURES/f-shim"
mkdir -p "$FIXTURE_F"
cat > "$FIXTURE_F/AGENTS.md" <<'EOF'
# AGENTS.md

## Critical Rules

- **C0.1** hand-authored rule one
EOF
cat > "$FIXTURE_F/CLAUDE.md" <<'EOF'
# Project

@AGENTS.md

## Claude Code only

- `.claude/rules/` auto-loads.
EOF

echo ""; echo "--- (f) CLAUDE.md is a shim: note printed, AGENTS.md untouched, exit 0 ---"
before_f="$(cat "$FIXTURE_F/AGENTS.md")"
rc_f=0
out_f="$(cd "$FIXTURE_F" && bash "$GEN" 2>&1)" || rc_f=$?
after_f="$(cat "$FIXTURE_F/AGENTS.md")"
if [ "$rc_f" -eq 0 ] && [ "$before_f" = "$after_f" ] \
   && [ ! -f "$FIXTURE_F/AGENTS.generated.md" ] \
   && grep -qF "canonical constitution" <<<"$out_f"; then
  echo "  PASS  shim detected: note printed, AGENTS.md untouched, no fallback file, exit 0"
else
  FAILS+=("(f) expected exit 0, unchanged AGENTS.md, a note, and no fallback file when CLAUDE.md is a shim. rc=$rc_f out=$out_f")
fi

echo ""; echo "--- (f) --force REFUSES to overwrite the canonical AGENTS.md (exit 1, file unchanged) ---"
rc_f2=0
out_f2="$(cd "$FIXTURE_F" && bash "$GEN" --force 2>&1)" || rc_f2=$?
after_f2="$(cat "$FIXTURE_F/AGENTS.md")"
if [ "$rc_f2" -eq 1 ] && [ "$before_f" = "$after_f2" ] \
   && [ ! -f "$FIXTURE_F/AGENTS.generated.md" ] \
   && grep -qF "canonical constitution" <<<"$out_f2"; then
  echo "  PASS  --force refused: exit 1, AGENTS.md unchanged, refusal names it as the canonical constitution"
else
  FAILS+=("(f) expected --force to exit 1 and leave the canonical AGENTS.md unchanged. rc=$rc_f2 out=$out_f2 file: $after_f2")
fi

# --- (g) a GENERATOR-MARKED AGENTS.md is this script's own prior output -----
# It is a references summary, not a constitution, so the canonical-AGENTS.md
# decline must NOT fire even beside a CLAUDE.md shim: a bare run and --force
# must both regenerate it exactly as they did before the inversion. Without the
# marker clause in constitution_file(), the script would permanently refuse to
# regenerate its own output in every shim repo.
FIXTURE_G="$TMPDIR_FIXTURES/g-marked-summary"
mkdir -p "$FIXTURE_G/.claude/references"
cat > "$FIXTURE_G/.claude/references/security-checklist.md" <<'EOF'
---
description: Baseline security checklist for any serious software change
---
# Security Checklist

## Input And Auth

- validate every external input
EOF
cat > "$FIXTURE_G/CLAUDE.md" <<'EOF'
# Project

@AGENTS.md

## Critical Rules

- **C0.1** rule one lives in CLAUDE.md, not the summary

## Claude Code only

- `.claude/rules/` auto-loads.
EOF
cat > "$FIXTURE_G/AGENTS.md" <<'EOF'
# AGENTS.md

> Auto-generated by MTK. Sections marked `## Custom:` are preserved across regeneration.
> This file provides project conventions to all AI coding assistants.

## Stale Summary

STALE_SUMMARY_MARKER_QX7 — a non-Custom section, so a real regeneration drops it.
EOF

echo ""; echo "--- (g) bare run REGENERATES a generator-marked AGENTS.md (shim present) ---"
rc_g=0
out_g="$(cd "$FIXTURE_G" && bash "$GEN" 2>&1)" || rc_g=$?
if [ "$rc_g" -eq 0 ] \
   && grep -qF "Auto-generated by MTK" "$FIXTURE_G/AGENTS.md" \
   && ! grep -qF "STALE_SUMMARY_MARKER_QX7" "$FIXTURE_G/AGENTS.md" \
   && [ ! -f "$FIXTURE_G/AGENTS.generated.md" ] \
   && ! grep -qF "canonical constitution" <<<"$out_g"; then
  echo "  PASS  marked AGENTS.md regenerated in place; no decline note, no fallback file"
else
  FAILS+=("(g) expected a bare run to regenerate the generator-marked AGENTS.md. rc=$rc_g out=$out_g")
fi

echo ""; echo "--- (g) --force also REGENERATES a generator-marked AGENTS.md ---"
printf '\n## Stale Again\n\nSTALE_AGAIN_QX8\n' >> "$FIXTURE_G/AGENTS.md"
rc_g2=0
out_g2="$(cd "$FIXTURE_G" && bash "$GEN" --force 2>&1)" || rc_g2=$?
if [ "$rc_g2" -eq 0 ] \
   && grep -qF "Auto-generated by MTK" "$FIXTURE_G/AGENTS.md" \
   && ! grep -qF "STALE_AGAIN_QX8" "$FIXTURE_G/AGENTS.md" \
   && ! grep -qF "REFUSING --force" <<<"$out_g2"; then
  echo "  PASS  --force regenerated the marked summary (no refusal)"
else
  FAILS+=("(g) expected --force to regenerate the generator-marked AGENTS.md. rc=$rc_g2 out=$out_g2")
fi

echo ""; echo "--- (g) the Critical Rules heading still names CLAUDE.md in a marked-summary repo ---"
if grep -qF "Critical Rules (from CLAUDE.md)" "$FIXTURE_G/AGENTS.md"; then
  echo "  PASS  heading resolves to CLAUDE.md, and the rule body came from it"
else
  FAILS+=("(g) expected the Critical Rules heading to name CLAUDE.md, got: $(grep 'Critical Rules' "$FIXTURE_G/AGENTS.md")")
fi

# --- (h) an explicit non-default output path is honoured in BOTH branches ---
# The decline note advertises "pass an explicit output path"; that option must
# not be inert. setup-refresh-plan.sh's row-5 regenerate-and-diff depends on it.
echo ""; echo "--- (h) canonical AGENTS.md + explicit output path: writes there, exit 0 ---"
before_h="$(cat "$FIXTURE_F/AGENTS.md")"
rc_h=0
out_h="$(cd "$FIXTURE_F" && bash "$GEN" AGENTS.summary.md 2>&1)" || rc_h=$?
after_h="$(cat "$FIXTURE_F/AGENTS.md")"
if [ "$rc_h" -eq 0 ] && [ "$before_h" = "$after_h" ] \
   && [ -f "$FIXTURE_F/AGENTS.summary.md" ] \
   && grep -qF "Auto-generated by MTK" "$FIXTURE_F/AGENTS.summary.md"; then
  echo "  PASS  summary written to the explicit path; canonical AGENTS.md untouched"
else
  FAILS+=("(h) expected an explicit output path to be honoured beside a canonical AGENTS.md. rc=$rc_h out=$out_h")
fi

echo ""; echo "--- (h) canonical AGENTS.md: the decline/refusal still fires for the default path ---"
rc_h2=0
out_h2="$(cd "$FIXTURE_F" && bash "$GEN" AGENTS.md 2>&1)" || rc_h2=$?
rc_h3=0
out_h3="$(cd "$FIXTURE_F" && bash "$GEN" --force AGENTS.md 2>&1)" || rc_h3=$?
if [ "$rc_h2" -eq 0 ] && grep -qF "canonical constitution" <<<"$out_h2" \
   && [ "$rc_h3" -eq 1 ] && grep -qF "canonical constitution" <<<"$out_h3" \
   && [ "$before_h" = "$(cat "$FIXTURE_F/AGENTS.md")" ]; then
  echo "  PASS  explicit AGENTS.md still declines (exit 0) and refuses --force (exit 1)"
else
  FAILS+=("(h) expected an explicit AGENTS.md target to keep the decline/refusal. rc2=$rc_h2 rc3=$rc_h3 out2=$out_h2 out3=$out_h3")
fi

# --- (i) --force ./AGENTS.md and an absolute path are the same protected target ---
FIXTURE_I="$TMPDIR_FIXTURES/i-force-identity"
mkdir -p "$FIXTURE_I"
printf '# Project\n\n## Critical Rules\n\n- **C0.1** hand-authored rule\n\n## Build\n\nmake\n' > "$FIXTURE_I/AGENTS.md"
printf '# Shim\n\n@AGENTS.md\n' > "$FIXTURE_I/CLAUDE.md"
before_i="$(cat "$FIXTURE_I/AGENTS.md")"
echo ""; echo "--- (i) --force with an equivalent output path is refused ---"
rc_rel=0; (cd "$FIXTURE_I" && bash "$GEN" --force ./AGENTS.md >/dev/null 2>&1) || rc_rel=$?
rc_abs=0; (cd "$FIXTURE_I" && bash "$GEN" --force "$FIXTURE_I/AGENTS.md" >/dev/null 2>&1) || rc_abs=$?
if [ "$rc_rel" -eq 1 ] && [ "$rc_abs" -eq 1 ] && [ "$(cat "$FIXTURE_I/AGENTS.md")" = "$before_i" ]; then
  echo "  PASS  ./AGENTS.md and the absolute path are refused (exit 1) and the constitution is byte-identical"
else
  FAILS+=("(i) expected exit 1 for both equivalent paths with AGENTS.md unchanged, got rel=$rc_rel abs=$rc_abs")
fi

echo ""
if [ ${#FAILS[@]} -gt 0 ]; then
  printf '  FAIL  %s\n' "${FAILS[@]}" >&2
  exit 1
fi
echo "========================================"
echo "TEST PASSED — all DF-6 generate-agents-md.sh assertions green"
