#!/usr/bin/env bash
set -euo pipefail

# generate-tool-configs.sh — constitution-aware pointer mode (agents-md-canonical WS1).
#
# Covers:
#   1. Legacy repo (CLAUDE.md only, no AGENTS.md): copilot/windsurf/cline emit
#      pointer mode sourced from CLAUDE.md — unchanged content, new shape.
#   2. Shim repo (AGENTS.md canonical — it exists, is NOT generator-marked, and
#      CLAUDE.md contains `^@AGENTS\.md`):
#      copilot/windsurf/cline pointer mode sources Critical Rules from
#      AGENTS.md, not CLAUDE.md.
#   3. Pointer mode output never exceeds 40 lines, even when the resolved
#      constitution's Critical Rules section is large (awk 'NR<=n' cap), and
#      a truncated file ends in a visible truncation marker plus a stderr
#      warning naming the dropped line count.
#   4. gemini keeps its full-content SHAPE (assemble_all_content, no
#      "Canonical instructions" pointer line) but sources Critical Rules from
#      the resolved constitution — in a shim repo that is AGENTS.md.
#   5. cursor-rules keeps its full-content SHAPE (.mdc rules) and likewise
#      sources mtk-critical-rules.mdc from the resolved constitution.
#   6. Overwrite guard is intact for pointer-mode formats: a hand-curated
#      file with no marker is left alone (warning printed, exit 0), and
#      --force overwrites it.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
GEN="$REPO_ROOT/scripts/generate-tool-configs.sh"

fail() { printf 'FAIL: %s\n' "$1" >&2; exit 1; }
ok()   { printf 'PASS: %s\n' "$1"; }

[ -f "$GEN" ] || fail "script not found: $GEN"
[ -x "$GEN" ] || fail "script not executable: $GEN"

SBX="$(mktemp -d -t mtk-toolconfigs-XXXXXX)"
trap 'rm -rf "$SBX"' EXIT

new_fixture() {
  local d; d="$(mktemp -d "$SBX/fixture-XXXXXX")"
  printf '%s' "$d"
}

# 1. Legacy repo: no AGENTS.md, plain CLAUDE.md constitution. copilot pointer
#    mode must source Critical Rules from CLAUDE.md, cap at 40 lines, name
#    AGENTS.md as canonical, and carry the marker.
F="$(new_fixture)"
cat > "$F/CLAUDE.md" <<'MD'
# Project

## Critical Rules

- **C0.1** legacy rule one
- **C0.2** legacy rule two
MD
(cd "$F" && bash "$GEN" --format copilot >/dev/null)
out="$(cat "$F/.github/copilot-instructions.md")"
grep -qF "Auto-generated by MTK" <<<"$out" || fail "legacy copilot: missing auto-generated marker"
grep -qF 'Canonical instructions: read `CLAUDE.md`.' <<<"$out" || fail "legacy copilot: pointer must name the resolved constitution (CLAUDE.md in a legacy repo)"
grep -qF "legacy rule one" <<<"$out" || fail "legacy copilot: Critical Rules body from CLAUDE.md missing"
[ "$(wc -l < "$F/.github/copilot-instructions.md" | tr -d ' ')" -le 40 ] || fail "legacy copilot: output exceeds 40 lines"
ok "legacy repo (CLAUDE.md only): copilot pointer mode sources Critical Rules from CLAUDE.md, <= 40 lines"

# 2. Shim repo: AGENTS.md is canonical (CLAUDE.md contains `@AGENTS.md`).
#    windsurf/cline pointer mode must source Critical Rules from AGENTS.md.
F="$(new_fixture)"
cat > "$F/AGENTS.md" <<'MD'
# AGENTS.md

## Critical Rules

- **C0.1** hand-authored rule from AGENTS.md
MD
cat > "$F/CLAUDE.md" <<'MD'
# Project

@AGENTS.md

## Claude Code only
MD
(cd "$F" && bash "$GEN" --format windsurf --format cline >/dev/null)
out_w="$(cat "$F/.windsurfrules")"
out_c="$(cat "$F/.clinerules")"
grep -qF "hand-authored rule from AGENTS.md" <<<"$out_w" || fail "shim windsurf: expected Critical Rules from AGENTS.md"
grep -qF "hand-authored rule from AGENTS.md" <<<"$out_c" || fail "shim cline: expected Critical Rules from AGENTS.md"
grep -qF 'Canonical instructions: read `AGENTS.md`.' <<<"$out_w" || fail "shim windsurf: missing AGENTS.md pointer line"
ok "shim repo (CLAUDE.md imports AGENTS.md): windsurf/cline pointer mode sources Critical Rules from AGENTS.md"

# 3. 40-line cap: a large Critical Rules section must be truncated, never
#    overrun, using the SIGPIPE-safe awk 'NR<=n' pattern (S3.17).
F="$(new_fixture)"
{
  echo "# Project"
  echo ""
  echo "## Critical Rules"
  echo ""
  i=1
  while [ "$i" -le 60 ]; do
    echo "- **C0.$i** rule number $i with some padding text to bulk it out"
    i=$((i + 1))
  done
} > "$F/CLAUDE.md"
warn_cap="$( (cd "$F" && bash "$GEN" --format cline >/dev/null) 2>&1 )"
lines="$(wc -l < "$F/.clinerules" | tr -d ' ')"
[ "$lines" -eq 40 ] || fail "40-line cap: expected exactly 40 lines for an oversized Critical Rules section, got $lines"
last_line="$(tail -1 "$F/.clinerules")"
grep -qF "truncated at the 40-line cap" <<<"$last_line" || fail "40-line cap: expected the last emitted line to be the truncation marker, got: $last_line"
grep -qE "truncated at the 40-line cap — [0-9]+ line\(s\) dropped" <<<"$warn_cap" || fail "40-line cap: expected a stderr warning naming the dropped line count, got: $warn_cap"
ok "pointer mode capped at 40 lines, last line is the truncation marker, dropped-line count warned on stderr"

# 4. gemini keeps full-content SHAPE (no pointer line) but sources Critical
#    Rules from the resolved constitution — AGENTS.md in this shim repo.
F="$(new_fixture)"
mkdir -p "$F/.claude/references"
cat > "$F/AGENTS.md" <<'MD'
# AGENTS.md

## Critical Rules

- **C0.1** AGENTS.md rule (must appear in GEMINI.md)
MD
cat > "$F/CLAUDE.md" <<'MD'
# Project

@AGENTS.md

## Claude Code only
MD
cat > "$F/.claude/references/architecture-principles.md" <<'MD'
---
description: test arch principles
---
# Architecture Principles

Some intro text.

## Layering
MD
# $F's CLAUDE.md is a realistic shim: it carries no Critical Rules of its
# own (they live in AGENTS.md). Reading CLAUDE.md directly would therefore
# emit a GEMINI.md and a cursor rule set with NO critical rules at all — the
# failure this asserts against. Both formats keep their full-content shape
# and take the rules from the resolved constitution.
(cd "$F" && bash "$GEN" --format gemini >/dev/null)
out_g="$(cat "$F/GEMINI.md")"
grep -qF "## Architecture Principles" <<<"$out_g" || fail "gemini: expected full Architecture Principles section (full-content mode)"
grep -qF "AGENTS.md rule" <<<"$out_g" || fail "gemini: expected Critical Rules from the resolved constitution (AGENTS.md)"
grep -qF "## Critical Rules (from AGENTS.md)" <<<"$out_g" || fail "gemini: expected the Critical Rules heading to name AGENTS.md as the source"
grep -qF "Canonical instructions" <<<"$out_g" && fail "gemini: must stay full-content mode, not switch to pointer mode"
ok "gemini stays full-content mode and sources Critical Rules from the resolved constitution (AGENTS.md)"

# 5. cursor-rules keeps its full-content shape and sources the always-apply
#    critical-rules .mdc from the resolved constitution.
(cd "$F" && bash "$GEN" --format cursor-rules >/dev/null)
[ -f "$F/.cursor/rules/mtk-architecture.mdc" ] || fail "cursor-rules: expected architecture .mdc file (full-content mode)"
[ -f "$F/.cursor/rules/mtk-critical-rules.mdc" ] || fail "cursor-rules: expected mtk-critical-rules.mdc built from the resolved constitution (AGENTS.md)"
grep -qF "AGENTS.md rule" "$F/.cursor/rules/mtk-critical-rules.mdc" || fail "cursor-rules: mtk-critical-rules.mdc must carry the AGENTS.md rules"
ok "cursor-rules stays full-content and sources mtk-critical-rules.mdc from the resolved constitution (AGENTS.md)"

# 6. Overwrite guard intact for pointer-mode formats: hand-curated file (no
#    marker) is left alone; --force overwrites it.
F="$(new_fixture)"
cat > "$F/CLAUDE.md" <<'MD'
# Project

## Critical Rules

- **C0.1** a rule
MD
mkdir -p "$F/.github"
printf '# Hand-curated, no marker here\n' > "$F/.github/copilot-instructions.md"
warn="$(cd "$F" && bash "$GEN" --format copilot 2>&1)"
grep -qF "refusing to overwrite hand-curated" <<<"$warn" || fail "overwrite guard: expected refusal warning, got: $warn"
grep -qF "Hand-curated, no marker here" "$F/.github/copilot-instructions.md" || fail "overwrite guard: hand-curated file was modified without --force"
(cd "$F" && bash "$GEN" --format copilot --force >/dev/null)
grep -qF "Auto-generated by MTK" "$F/.github/copilot-instructions.md" || fail "overwrite guard: --force did not overwrite hand-curated file"
ok "overwrite guard intact for pointer-mode formats: refuses without marker, --force overwrites"

# 6. Generator-marked AGENTS.md (the legacy references summary) beside a real
#    CLAUDE.md constitution, with the shim line present. The marker disqualifies
#    AGENTS.md, so the emitted configs must carry CLAUDE.md's rules — inlining a
#    generated summary's headings would ship pointers to every non-Claude tool
#    as if they were the governing rules.
F="$(new_fixture)"
cat > "$F/AGENTS.md" <<'MD'
# AGENTS.md

> Auto-generated by MTK. Sections marked `## Custom:` are preserved across regeneration.

## Critical Rules

- **C9.1** SUMMARY_RULE_MARKER must never reach a generated config
MD
cat > "$F/CLAUDE.md" <<'MD'
# Project

@AGENTS.md

## Critical Rules

- **C0.1** REAL_RULE_MARKER from the CLAUDE.md constitution
MD
(cd "$F" && bash "$GEN" --format windsurf --format cline >/dev/null)
out_w="$(cat "$F/.windsurfrules")"
out_c="$(cat "$F/.clinerules")"
grep -qF "REAL_RULE_MARKER" <<<"$out_w" || fail "marked AGENTS.md windsurf: expected Critical Rules from CLAUDE.md, got: $out_w"
grep -qF "REAL_RULE_MARKER" <<<"$out_c" || fail "marked AGENTS.md cline: expected Critical Rules from CLAUDE.md, got: $out_c"
grep -qF "SUMMARY_RULE_MARKER" <<<"$out_w" && fail "marked AGENTS.md windsurf: the generated summary's rules leaked into the config"
grep -qF "SUMMARY_RULE_MARKER" <<<"$out_c" && fail "marked AGENTS.md cline: the generated summary's rules leaked into the config"
ok "generator-marked AGENTS.md is skipped: pointer configs source Critical Rules from CLAUDE.md"

# 7. The marker only counts within the first 10 lines — a hand-authored
#    AGENTS.md that merely MENTIONS the string further down stays canonical.
F="$(new_fixture)"
{ printf '# AGENTS.md\n\n## Critical Rules\n\n'
  printf -- '- **C0.1** AUTHORED_RULE_MARKER from a hand-written AGENTS.md\n\n'
  printf '## Notes\n\n'
  for i in 1 2 3 4 5 6 7 8 9 10; do printf 'filler %%s\n' "$i"; done
  printf '\nThe legacy summary carries "Auto-generated by MTK" in its header.\n'
} > "$F/AGENTS.md"
printf '# Project\n\n@AGENTS.md\n' > "$F/CLAUDE.md"
(cd "$F" && bash "$GEN" --format windsurf >/dev/null)
grep -qF "AUTHORED_RULE_MARKER" "$F/.windsurfrules" || fail "late marker: expected Critical Rules from the hand-authored AGENTS.md, got: $(cat "$F/.windsurfrules")"
ok "the marker string below line 10 does not demote a hand-authored AGENTS.md"

# --- legacy pointer names the resolved constitution (PR #108 Codex review) ---
# In a CLAUDE.md-only repo the pointer line and the truncation notice must
# name CLAUDE.md — a pointer to a nonexistent AGENTS.md strands the rules the
# 40-line cap drops.
LEG="$(mktemp -d)"
{ echo "# Project"; echo; echo "## Critical Rules (Always Apply)"; echo; for i in $(seq 1 60); do echo "- **C0.$i** legacy rule $i"; done; } > "$LEG/CLAUDE.md"
(cd "$LEG" && bash "$GEN" --format copilot >/dev/null 2>"$LEG/err") || fail "legacy pointer: generator exited non-zero"
grep -q 'Canonical instructions: read `CLAUDE.md`' "$LEG/.github/copilot-instructions.md" || fail "legacy pointer: expected the pointer line to name CLAUDE.md, got: $(grep -n 'Canonical instructions' "$LEG/.github/copilot-instructions.md")"
grep -q 'full rules in CLAUDE.md' "$LEG/.github/copilot-instructions.md" || fail "legacy pointer: truncation marker should name CLAUDE.md"
grep -q 'full rules in CLAUDE.md' "$LEG/err" || fail "legacy pointer: stderr truncation note should name CLAUDE.md"
if grep -q 'AGENTS.md' "$LEG/.github/copilot-instructions.md"; then fail "legacy pointer: output must not mention a nonexistent AGENTS.md"; fi
ok "legacy repo: pointer + truncation notices name the resolved constitution (CLAUDE.md)"

echo "test-generate-tool-configs: all checks passed"
