#!/usr/bin/env bash
set -euo pipefail

# Rule enforcement map (round 8, option D): rules naming a live wired
# enforcer read WIRED, rules naming a missing one read BROKEN, rules naming
# nothing read PROSE (not a failure), and hooks no rule documents surface as
# UNDOC. Token boundaries hold (checksums.sha256 is not checksums.sh).

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
MAP="$REPO_ROOT/scripts/rule-enforcement-map.sh"

fail() { printf 'FAIL: %s\n' "$1" >&2; exit 1; }

WORK="$(mktemp -d)"
cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT
git -C "$WORK" init -q
cd "$WORK"
mkdir -p .claude/rules hooks scripts

printf '#!/usr/bin/env bash\nset -euo pipefail\n' > hooks/live-guard.sh
printf '#!/usr/bin/env bash\nset -euo pipefail\n' > hooks/orphan-hook.sh
printf '#!/usr/bin/env bash\nset -euo pipefail\n' > scripts/checker.sh
cat > hooks/hooks.json <<'EOF'
{ "hooks": { "PreToolUse": [ { "hooks": [ { "type": "command", "command": "${CLAUDE_PLUGIN_ROOT}/hooks/live-guard.sh" } ] } ] } }
EOF

cat > .claude/rules/test-rules.md <<'EOF'
# Rules

- **S9.1** Enforced by `hooks/live-guard.sh` on every call.
- **S9.2** Checked by `scripts/checker.sh` before release; regenerate `checksums.sha256` after.
- **S9.3** Enforced by `hooks/ghost-guard.sh` which was deleted long ago.
- **S9.4** Be sensible. Use good judgment.
- **S9.5** The orphan hook is deliberately mentioned here: orphan-hook.
EOF
printf '# P\n\n- **C0.1** Never do the bad thing.\n' > CLAUDE.md

out="$(CLAUDE_PROJECT_DIR="$WORK" bash "$MAP")"
rc=$?
[ "$rc" -eq 0 ] || fail "default posture must exit 0 (got $rc)"

case "$out" in *'WIRED   S9.1'*) : ;; *) fail "live wired hook must read WIRED. Got: $out" ;; esac
case "$out" in *'WIRED   S9.2'*) : ;; *) fail "existing script enforcer must read WIRED. Got: $out" ;; esac
case "$out" in *'BROKEN  S9.3'*'ghost-guard.sh'*) : ;; *) fail "missing enforcer must read BROKEN. Got: $out" ;; esac
case "$out" in *'PROSE   S9.4'*) : ;; *) fail "no-enforcer rule must read PROSE. Got: $out" ;; esac
case "$out" in *'checksums.sh (file missing)'*) fail "checksums.sha256 must not token-match checksums.sh" ;; *) : ;; esac
printf '  PASS  WIRED / BROKEN / PROSE verdicts with clean token boundaries\n'

case "$out" in *'UNDOC'*'orphan-hook.sh'*) fail "orphan-hook is mentioned by S9.5 (spaced/stem) — must not be UNDOC" ;; *) : ;; esac
printf '  PASS  prose mention counts as documentation\n'

# Undocumented hook detection: add one nothing mentions.
printf '#!/usr/bin/env bash\nset -euo pipefail\n' > hooks/mystery-hook.sh
out="$(CLAUDE_PROJECT_DIR="$WORK" bash "$MAP")"
case "$out" in *'UNDOC   hooks/mystery-hook.sh'*) : ;; *) fail "undocumented hook must surface as UNDOC. Got: $out" ;; esac
printf '  PASS  undocumented enforcer surfaces\n'

rc=0
CLAUDE_PROJECT_DIR="$WORK" bash "$MAP" --strict >/dev/null 2>&1 || rc=$?
[ "$rc" -eq 1 ] || fail "--strict must exit 1 with broken/undocumented present (got $rc)"
printf '  PASS  --strict exits non-zero on findings\n'

# --- Constitution resolution: AGENTS.md-first (shim-aware) ------------------
# The map reads the numbered Critical Rules from the RESOLVED constitution:
# AGENTS.md when it exists, is NOT generator-marked (`Auto-generated by MTK` in
# its first 10 lines), and CLAUDE.md is absent or a shim (`^@AGENTS.md`);
# otherwise CLAUDE.md. A legacy repo must behave exactly as before.

# $1 = fixture name. Creates <WORK>/<name> with a wired hook, one PROSE rule
# file, and nothing else; the caller writes the constitution file(s).
make_const_fixture() {
  local d="$WORK/$1"
  mkdir -p "$d/.claude/rules" "$d/hooks"
  git -C "$d" init -q
  printf '#!/usr/bin/env bash\nset -euo pipefail\n' > "$d/hooks/live-guard.sh"
  cat > "$d/hooks/hooks.json" <<'EOF'
{ "hooks": { "PreToolUse": [ { "hooks": [ { "type": "command", "command": "${CLAUDE_PLUGIN_ROOT}/hooks/live-guard.sh" } ] } ] } }
EOF
  printf '# Rules\n\n- **S8.1** Be sensible. Use good judgment.\n' > "$d/.claude/rules/base.md"
  printf '%s\n' "$d"
}

AGENTS_RULE='# AGENTS\n\n## Critical Rules\n\n- **C9.1** Enforced by `hooks/live-guard.sh` on every call.\n'
CLAUDE_RULE='# P\n\n- **C9.2** Enforced by `hooks/ghost-guard.sh` which was deleted long ago.\n'

# 1. AGENTS.md only (no CLAUDE.md) — rules come from AGENTS.md.
d="$(make_const_fixture const-agents-only)"
printf "$AGENTS_RULE" > "$d/AGENTS.md"
out="$(CLAUDE_PROJECT_DIR="$d" bash "$MAP")"
case "$out" in *'WIRED   C9.1'*) : ;; *) fail "AGENTS.md-only: rule from AGENTS.md must be classified. Got: $out" ;; esac
printf '  PASS  AGENTS.md-only repo: rules read from AGENTS.md\n'

# 2. CLAUDE.md shim (`@AGENTS.md`) + AGENTS.md — AGENTS.md wins; the shim's own
#    rule text is not read (it is a pointer, not a constitution).
d="$(make_const_fixture const-shim)"
printf "$AGENTS_RULE" > "$d/AGENTS.md"
{ printf '@AGENTS.md\n\n'; printf "$CLAUDE_RULE"; } > "$d/CLAUDE.md"
out="$(CLAUDE_PROJECT_DIR="$d" bash "$MAP")"
case "$out" in *'WIRED   C9.1'*) : ;; *) fail "shim: rule from AGENTS.md must be classified. Got: $out" ;; esac
case "$out" in *'C9.2'*) fail "shim: CLAUDE.md shim text must not be read as the constitution. Got: $out" ;; *) : ;; esac
printf '  PASS  CLAUDE.md shim resolves to AGENTS.md\n'

# 3. Legacy: CLAUDE.md only, no AGENTS.md — unchanged behavior.
d="$(make_const_fixture const-legacy)"
printf "$CLAUDE_RULE" > "$d/CLAUDE.md"
out="$(CLAUDE_PROJECT_DIR="$d" bash "$MAP")"
case "$out" in *'BROKEN  C9.2'*'ghost-guard.sh'*) : ;; *) fail "legacy: CLAUDE.md rules must still be classified. Got: $out" ;; esac
printf '  PASS  legacy CLAUDE.md-only repo unchanged\n'

# 4. Generator-marked AGENTS.md (the legacy references summary) beside a real
#    CLAUDE.md shim — the marker disqualifies AGENTS.md, so the map must read
#    CLAUDE.md. Mapping a generated summary's headings would report the wrong
#    rules as unwired.
d="$(make_const_fixture const-marked)"
{ printf '# AGENTS.md\n\n'
  printf '> Auto-generated by MTK. Sections marked `## Custom:` are preserved across regeneration.\n\n'
  printf '## Critical Rules\n\n'
  printf -- '- **C9.1** Enforced by `hooks/live-guard.sh` on every call.\n'
} > "$d/AGENTS.md"
{ printf '@AGENTS.md\n\n'; printf "$CLAUDE_RULE"; } > "$d/CLAUDE.md"
out="$(CLAUDE_PROJECT_DIR="$d" bash "$MAP")"
case "$out" in *'BROKEN  C9.2'*'ghost-guard.sh'*) : ;; *) fail "marked AGENTS.md: rules must come from CLAUDE.md. Got: $out" ;; esac
case "$out" in *'C9.1'*) fail "marked AGENTS.md: the generated summary must not be read as the constitution. Got: $out" ;; *) : ;; esac
printf '  PASS  generator-marked AGENTS.md is skipped; CLAUDE.md is the constitution\n'

printf '\nAll rule-enforcement-map checks passed.\n'
