#!/usr/bin/env bash
set -euo pipefail

# test-resolve-constitution.sh — the constitution-resolution matrix, owned once.
#
# Before scripts/resolve-constitution.sh existed this predicate was copy-pasted
# into nine callers and each caller's test rebuilt the same four fixtures. The
# matrix now lives here; caller tests keep a single case proving they DELEGATE.
#
# Covers both modes:
#   canonical — "which file holds the rules" (generator-marker clause applies)
#   --loaded  — "which bytes enter every session" (marker clause does NOT apply)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RC="$REPO_ROOT/scripts/resolve-constitution.sh"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

FAILS=()
ok()   { echo "  PASS  $1"; }
fail() { FAILS+=("$1"); echo "  FAIL  $1" >&2; }

# check <fixture> <mode> <expected> <label>
check() {
  local fx="$1" mode="$2" expected="$3" label="$4" got
  if [ "$mode" = "loaded" ]; then
    got="$(cd "$TMP/$fx" && bash "$RC" --loaded)"
  else
    got="$(cd "$TMP/$fx" && bash "$RC")"
  fi
  if [ "$got" = "$expected" ]; then
    ok "$label"
  else
    fail "$label — expected '$expected', got '$got'"
  fi
}

MARKED='# AGENTS.md

> Auto-generated by MTK. Sections marked `## Custom:` are preserved across regeneration.
'

mk() { mkdir -p "$TMP/$1"; }

# (a) legacy: CLAUDE.md only
mk a; printf '# Constitution\n' > "$TMP/a/CLAUDE.md"
# (b) inverted: AGENTS.md + shim
mk b; printf '# Constitution\n' > "$TMP/b/AGENTS.md"; printf '@AGENTS.md\n' > "$TMP/b/CLAUDE.md"
# (c) generator-marked AGENTS.md beside a real CLAUDE.md
mk c; printf '%s' "$MARKED" > "$TMP/c/AGENTS.md"; printf '# Constitution\n' > "$TMP/c/CLAUDE.md"
# (d) AGENTS.md only
mk d; printf '# Constitution\n' > "$TMP/d/AGENTS.md"
# (e) CLAUDE.md is a SYMLINK to AGENTS.md
mk e; printf '# Constitution\n' > "$TMP/e/AGENTS.md"; ln -s AGENTS.md "$TMP/e/CLAUDE.md"
# (f) neither file
mk f
# (g) both real: AGENTS.md exists but CLAUDE.md is a genuine constitution
mk g; printf '# Routing notes\n' > "$TMP/g/AGENTS.md"; printf '# Constitution\n' > "$TMP/g/CLAUDE.md"
# (h) generator-marked AGENTS.md imported by a shim
mk h; printf '%s' "$MARKED" > "$TMP/h/AGENTS.md"; printf '@AGENTS.md\n' > "$TMP/h/CLAUDE.md"
# (i) marker present but BELOW line 10 — must not demote a hand-authored file
mk i; { printf '# Constitution\n'; for n in $(seq 1 12); do printf 'line %s\n' "$n"; done; \
        printf 'Auto-generated by MTK\n'; } > "$TMP/i/AGENTS.md"
printf '@AGENTS.md\n' > "$TMP/i/CLAUDE.md"

echo "--- canonical mode: which file holds the rules ---"
check a canonical CLAUDE.md "legacy CLAUDE.md-only repo resolves to CLAUDE.md"
check b canonical AGENTS.md "AGENTS.md + @AGENTS.md shim resolves to AGENTS.md"
check c canonical CLAUDE.md "generator-marked AGENTS.md never outranks a real CLAUDE.md"
check d canonical AGENTS.md "AGENTS.md alone resolves to AGENTS.md"
check e canonical AGENTS.md "CLAUDE.md symlinked to AGENTS.md cannot be a shim for it"
check f canonical CLAUDE.md "no constitution at all still answers CLAUDE.md"
check g canonical CLAUDE.md "a real CLAUDE.md beside a non-shim AGENTS.md wins"
check h canonical CLAUDE.md "generator-marked AGENTS.md is not canonical even behind a shim"
check i canonical AGENTS.md "the marker below line 10 does not demote a hand-authored AGENTS.md"

echo ""
echo "--- --loaded mode: which bytes enter every session ---"
check a loaded CLAUDE.md "legacy repo loads CLAUDE.md"
check b loaded AGENTS.md "shim pulls AGENTS.md in"
check c loaded CLAUDE.md "real CLAUDE.md suppresses AGENTS.md"
check d loaded AGENTS.md "AGENTS.md alone loads directly"
check e loaded AGENTS.md "symlinked CLAUDE.md loads AGENTS.md"
check f loaded ""          "no constitution loads nothing"
check h loaded AGENTS.md "a MARKED AGENTS.md behind a shim still costs context (marker is canonical-only)"

echo ""
echo "--- flags ---"
if bash "$RC" --explain "$TMP/b" 2>&1 >/dev/null | grep -q 'resolve-constitution:'; then
  ok "--explain writes its reason to stderr"
else
  fail "--explain did not write a reason to stderr"
fi
if [ "$(bash "$RC" "$TMP/b")" = "$TMP/b/AGENTS.md" ]; then
  ok "a target directory is prefixed onto the answer"
else
  fail "target-dir prefix wrong: got '$(bash "$RC" "$TMP/b")'"
fi
rc_flag=0; bash "$RC" --nope >/dev/null 2>&1 || rc_flag=$?
if [ "$rc_flag" -eq 2 ]; then
  ok "an unknown flag exits 2"
else
  fail "expected exit 2 for an unknown flag, got $rc_flag"
fi

echo ""
if [ ${#FAILS[@]} -gt 0 ]; then
  printf 'FAILED: %s\n' "${FAILS[@]}" >&2
  exit 1
fi
echo "========================================"
echo "test-resolve-constitution: all checks passed"
