#!/usr/bin/env bash
set -euo pipefail

# build-rule-index.sh — Generate the rule "wake-up" layer (.claude/rules/INDEX.md).
#
# An always-on, token-budgeted index
# of rules indexed on three axes (decision / topic / scope). Agents read INDEX.md
# first (cheap), then pull a full rule file only when its axes match the task.
#
# Usage:
#   bash scripts/build-rule-index.sh           # (re)generate .claude/rules/INDEX.md
#   bash scripts/build-rule-index.sh --check    # exit 1 if INDEX.md is stale (CI)
#
# Budget target: keep the generated index under BUDGET_LINES lines so the
# always-on layer stays cheap. The script warns (non-fatal) if exceeded.

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

RULES_DIR=".claude/rules"
INDEX_FILE="$RULES_DIR/INDEX.md"
BUDGET_LINES=60

MODE="generate"
[ "${1:-}" = "--check" ] && MODE="check"

# Extract a single scalar from the `axes:` block of a rule file's frontmatter.
# Args: <file> <key>  -> prints value or "-"
axis_value() {
  local file="$1" key="$2"
  awk -v key="$key" '
    NR==1 && $0!="---" { exit }            # no frontmatter
    /^---[[:space:]]*$/ { fm++; if (fm==2) exit; next }
    fm==1 && /^axes:[[:space:]]*$/ { inaxes=1; next }
    fm==1 && inaxes && /^[a-zA-Z]/ { inaxes=0 }   # left the axes block
    fm==1 && inaxes && $1==key":" { print $2; found=1; exit }
    END { if (!found) print "-" }
  ' "$file"
}

# First H1 title (strip leading "# ").
rule_title() {
  grep -m1 '^# ' "$1" | sed 's/^# //'
}

# Rule-id prefix, e.g. "S1" from "Cite rules as S1.N".
rule_prefix() {
  grep -m1 -oE 'Cite rules as [A-Z][0-9]+' "$1" | sed 's/Cite rules as //' || true
}

generate() {
  local total_files=0
  {
    echo "# Rule Index — Wake-Up Layer"
    echo
    echo "> GENERATED by \`scripts/build-rule-index.sh\` — do not edit by hand."
    echo "> Run the script (or \`--check\` in CI) after editing any rule file."
    echo
    echo "This is the always-on layer. Read it first. Pull a full rule file from"
    echo "\`.claude/rules/\` **only** when its axes match the active task — e.g. load"
    echo "\`topic: hooks\` rules when editing \`hooks/\`, \`topic: git\` rules when"
    echo "branching/committing. Loading every rule eagerly defeats the budget."
    echo
    echo "Axes: **decision** (structure|process|authoring|security) ·"
    echo "**topic** (manifest|skills|hooks|git|…) · **scope** (global|project)."
    echo
    echo "| Rule file | Title | decision | topic | scope | Rules | Lines |"
    echo "|---|---|---|---|---|---|---|"
    local f
    for f in "$RULES_DIR"/*.md; do
      [ -e "$f" ] || continue
      local base; base="$(basename "$f")"
      [ "$base" = "INDEX.md" ] && continue
      total_files=$((total_files + 1))
      local title prefix dec top scope lines rules
      title="$(rule_title "$f")"; [ -z "$title" ] && title="$base"
      prefix="$(rule_prefix "$f")"
      dec="$(axis_value "$f" decision)"
      top="$(axis_value "$f" topic)"
      scope="$(axis_value "$f" scope)"
      lines="$(wc -l < "$f" | tr -d ' ')"
      if [ -n "$prefix" ]; then
        rules="$(grep -cE "^- \*\*${prefix}\." "$f" || true)"
        rules="${prefix}: ${rules}"
      else
        rules="-"
      fi
      echo "| \`$base\` | $title | $dec | $top | $scope | $rules | $lines |"
    done
    echo
    echo "_Fetch on demand: \`Read .claude/rules/<file>\`. Index regenerated by build-rule-index.sh._"
  }
}

if [ "$MODE" = "check" ]; then
  if [ ! -f "$INDEX_FILE" ]; then
    echo "STALE: $INDEX_FILE missing — run scripts/build-rule-index.sh" >&2
    exit 1
  fi
  tmp="$(mktemp)"
  generate > "$tmp"
  if ! diff -q "$INDEX_FILE" "$tmp" >/dev/null 2>&1; then
    echo "STALE: $INDEX_FILE does not match current rules — run scripts/build-rule-index.sh" >&2
    rm -f "$tmp"
    exit 1
  fi
  rm -f "$tmp"
  echo "OK: $INDEX_FILE is up to date"
  exit 0
fi

generate > "$INDEX_FILE"
n_lines="$(wc -l < "$INDEX_FILE" | tr -d ' ')"
echo "Wrote $INDEX_FILE ($n_lines lines, budget $BUDGET_LINES)"
if [ "$n_lines" -gt "$BUDGET_LINES" ]; then
  echo "WARN: wake-up index exceeds budget ($n_lines > $BUDGET_LINES) — consider trimming." >&2
fi
