#!/usr/bin/env bash
# Build .claude/triggers.index from skill frontmatter.
# Scans every MTK-managed skill for `triggers:` in frontmatter and emits
# tab-separated records: <keyword><TAB><skill-name>
#
# The triggers hook (hooks/lib/trigger-hints.sh) grep-scans the user prompt
# and tool outputs against this index, surfacing "consider skill X" nudges.
#
# Usage: bash scripts/build-triggers-index.sh          # rebuild in place
#        bash scripts/build-triggers-index.sh --check  # fail on drift, no writes
# Writes to: .claude/triggers.index (overwritten in default mode)

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

INDEX_FILE=".claude/triggers.index"

MODE="build"
if [ "${1:-}" = "--check" ]; then
  MODE="check"
fi

generate() {
  printf '# MTK triggers index — generated by scripts/build-triggers-index.sh\n'
  printf '# Format: <keyword>\\t<skill-name>\n'
  printf '# Scanned from .claude/skills/*/SKILL.md frontmatter `triggers:` key\n'

  for skill in .claude/skills/*/SKILL.md; do
    [ -f "$skill" ] || continue
    skill_name="$(basename "$(dirname "$skill")")"

    # Extract frontmatter block (between first two `---` lines)
    fm="$(awk '/^---$/{n++; next} n==1{print} n>=2{exit}' "$skill")"

    # `triggers:` may be inline array `[a, b]` or YAML list of `- item` entries.
    triggers_line="$(printf '%s\n' "$fm" | grep -E '^triggers:' | head -1 || true)"
    [ -z "$triggers_line" ] && continue

    # Inline array form: triggers: [auth, payments, pii]
    if echo "$triggers_line" | grep -qE '^triggers:[[:space:]]*\['; then
      echo "$triggers_line" | \
        sed -E 's/^triggers:[[:space:]]*\[([^]]*)\].*/\1/' | \
        tr ',' '\n' | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//' | \
        while IFS= read -r kw; do
          [ -n "$kw" ] && printf '%s\t%s\n' "$kw" "$skill_name"
        done
    else
      # YAML list form (items `- item` following the `triggers:` line,
      # stopping at next top-level key).
      printf '%s\n' "$fm" | awk '
        /^triggers:[[:space:]]*$/ { in_t=1; next }
        in_t && /^[[:space:]]*-[[:space:]]/ {
          sub(/^[[:space:]]*-[[:space:]]*/, "")
          sub(/[[:space:]]+$/, "")
          gsub(/"/, "")
          print
          next
        }
        in_t && /^[^[:space:]-]/ { in_t=0 }
      ' | while IFS= read -r kw; do
        [ -n "$kw" ] && printf '%s\t%s\n' "$kw" "$skill_name"
      done
    fi
  done
}

if [ "$MODE" = "check" ]; then
  if [ ! -f "$INDEX_FILE" ]; then
    echo "STALE: $INDEX_FILE missing — run scripts/build-triggers-index.sh" >&2
    exit 1
  fi
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  generate > "$tmp"
  if ! diff -q "$INDEX_FILE" "$tmp" >/dev/null 2>&1; then
    echo "STALE: $INDEX_FILE does not match skill frontmatter — run scripts/build-triggers-index.sh" >&2
    exit 1
  fi
  echo "OK: $INDEX_FILE is up to date"
  exit 0
fi

TMP="${INDEX_FILE}.tmp.$$"
trap 'rm -f "$TMP"' EXIT
generate > "$TMP"
mv "$TMP" "$INDEX_FILE"
count="$(grep -cv '^#' "$INDEX_FILE" 2>/dev/null || echo 0)"
printf 'Triggers index built: %s entries → %s\n' "$count" "$INDEX_FILE"
