#!/usr/bin/env bash
set -euo pipefail

# build-rule-index.sh — Generate the rule "wake-up" layer (.claude/rules/INDEX.md).
#
# An always-on, token-budgeted index
# of rules indexed on three axes (decision / topic / scope). Agents read INDEX.md
# first (cheap), then pull a full rule file only when its axes match the task.
#
# Usage:
#   bash scripts/build-rule-index.sh           # (re)generate .claude/rules/INDEX.md
#   bash scripts/build-rule-index.sh --check    # exit 1 if INDEX.md is stale (CI)
#
# Budget target: keep the generated index under BUDGET_LINES lines so the
# always-on layer stays cheap. The script warns (non-fatal) if exceeded.

# Root on the PROJECT, not on the script's own location. This script is invoked
# from the plugin cache when bootstrapping a target repo; `dirname $0/..` would
# regenerate the PLUGIN's index and leave the target with no INDEX.md — so every
# rule file there loads eagerly on every request, forever, which is precisely the
# cost this index exists to remove. Same contract as spec-archive.sh / lint-ears.sh
# (CLAUDE.md: target-repo scripts resolve the project root from
# $CLAUDE_PROJECT_DIR/git so output lands in the target wherever the script lives).
ROOT_DIR="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$ROOT_DIR"

RULES_DIR=".claude/rules"
INDEX_FILE="$RULES_DIR/INDEX.md"
TRIGGERS_FILE="$RULES_DIR/triggers.index"
BUDGET_LINES=60

MODE="generate"
[ "${1:-}" = "--check" ] && MODE="check"

# Extract a single scalar from the `axes:` block of a rule file's frontmatter.
# Args: <file> <key>  -> prints value or "-"
axis_value() {
  local file="$1" key="$2"
  awk -v key="$key" '
    NR==1 && $0!="---" { exit }            # no frontmatter
    /^---[[:space:]]*$/ { fm++; if (fm==2) exit; next }
    fm==1 && /^axes:[[:space:]]*$/ { inaxes=1; next }
    fm==1 && inaxes && /^[a-zA-Z]/ { inaxes=0 }   # left the axes block
    fm==1 && inaxes && $1==key":" { print $2; found=1; exit }
    END { if (!found) print "-" }
  ' "$file"
}

# Collect the `paths:` glob list from frontmatter, joined by "; " (or "-" if none).
# These drive machine-scoped auto-attach: a rule whose glob matches a touched file
# is always relevant, independent of the axes.
paths_value() {
  awk '
    NR==1 && $0!="---" { exit }
    /^---[[:space:]]*$/ { fm++; if (fm==2) exit; next }
    fm==1 && /^paths:[[:space:]]*$/ { inp=1; next }
    fm==1 && inp && /^[a-zA-Z]/ { inp=0 }
    fm==1 && inp && /^[[:space:]]*-[[:space:]]/ {
      item=$0; sub(/^[[:space:]]*-[[:space:]]*/,"",item); gsub(/"/,"",item)
      out = (out=="" ? item : out "; " item)
    }
    END { if (out=="") print "-"; else print out }
  ' "$1"
}

# Extract a scalar from the `trigger:` block (tool / pattern / path) -> value or "-".
# Values may be quoted; quotes are stripped. Everything after the key is taken
# verbatim so ERE patterns containing spaces or ':' survive intact.
trigger_value() {
  local file="$1" key="$2"
  awk -v key="$key" '
    NR==1 && $0!="---" { exit }
    /^---[[:space:]]*$/ { fm++; if (fm==2) exit; next }
    fm==1 && /^trigger:[[:space:]]*$/ { intr=1; next }
    fm==1 && intr && /^[a-zA-Z]/ { intr=0 }
    fm==1 && intr && $0 ~ "^[[:space:]]+" key ":" {
      line=$0
      sub("^[[:space:]]+" key ":[[:space:]]*", "", line)
      gsub(/^"|"$/, "", line)
      print line; found=1; exit
    }
    END { if (!found) print "-" }
  ' "$file"
}

# Top-level `strength:` scalar -> inject | require-read | block (default inject).
strength_value() {
  awk '
    NR==1 && $0!="---" { exit }
    /^---[[:space:]]*$/ { fm++; if (fm==2) exit; next }
    fm==1 && /^strength:[[:space:]]*/ {
      line=$0; sub(/^strength:[[:space:]]*/, "", line); gsub(/^"|"$/, "", line)
      print line; found=1; exit
    }
    END { if (!found) print "inject" }
  ' "$1"
}

# First H1 title (strip leading "# ").
rule_title() {
  grep -m1 '^# ' "$1" | sed 's/^# //'
}

# Rule-id prefix, e.g. "S1" from "Cite rules as S1.N".
rule_prefix() {
  grep -m1 -oE 'Cite rules as [A-Z][0-9]+' "$1" | sed 's/Cite rules as //' || true
}

generate() {
  local total_files=0
  {
    echo "# Rule Index — Wake-Up Layer"
    echo
    echo "> GENERATED by \`scripts/build-rule-index.sh\` — do not edit by hand."
    echo "> Run the script (or \`--check\` in CI) after editing any rule file."
    echo
    echo "This is the always-on layer. Read it first. Pull a full rule file from"
    echo "\`.claude/rules/\` **only** when its axes match the active task — e.g. load"
    echo "\`topic: hooks\` rules when editing \`hooks/\`, \`topic: git\` rules when"
    echo "branching/committing. Loading every rule eagerly defeats the budget."
    echo
    echo "Axes: **decision** (structure|process|authoring|security) ·"
    echo "**topic** (manifest|skills|hooks|git|…) · **scope** (global|project)."
    echo "**paths** lists file globs — a rule whose glob matches a touched file is"
    echo "always relevant (machine-scoped auto-attach), independent of the axes."
    echo
    echo "| Rule file | Title | decision | topic | scope | paths | Rules | Lines |"
    echo "|---|---|---|---|---|---|---|---|"
    local f
    for f in "$RULES_DIR"/*.md; do
      [ -e "$f" ] || continue
      local base; base="$(basename "$f")"
      [ "$base" = "INDEX.md" ] && continue
      total_files=$((total_files + 1))
      local title prefix dec top scope paths lines rules
      title="$(rule_title "$f")"; [ -z "$title" ] && title="$base"
      prefix="$(rule_prefix "$f")"
      dec="$(axis_value "$f" decision)"
      top="$(axis_value "$f" topic)"
      scope="$(axis_value "$f" scope)"
      paths="$(paths_value "$f")"
      lines="$(wc -l < "$f" | tr -d ' ')"
      if [ -n "$prefix" ]; then
        rules="$(grep -cE "^- \*\*${prefix}\." "$f" || true)"
        rules="${prefix}: ${rules}"
      else
        rules="-"
      fi
      echo "| \`$base\` | $title | $dec | $top | $scope | $paths | $rules | $lines |"
    done
    echo
    echo "_Fetch on demand: \`Read .claude/rules/<file>\`. Index regenerated by build-rule-index.sh._"
  }
}

# The machine-readable half of the wake-up layer. INDEX.md is for the model to
# read; triggers.index is for hooks/rule-trigger.sh to match against on every
# tool call — so it is tab-separated, ordered, and cheap to scan.
# Columns: name <TAB> tool <TAB> pattern <TAB> path <TAB> strength <TAB> source
generate_triggers() {
  echo "# GENERATED by scripts/build-rule-index.sh — do not edit by hand."
  echo "# name	tool	pattern	path	strength	source"
  local f
  for f in "$RULES_DIR"/*.md; do
    [ -e "$f" ] || continue
    local base; base="$(basename "$f")"
    [ "$base" = "INDEX.md" ] && continue
    local tool pattern path strength
    tool="$(trigger_value "$f" tool)"
    # No `tool:` means the rule declares no trigger — skip it entirely rather
    # than emitting a wildcard row that would fire on every single tool call.
    [ "$tool" = "-" ] && continue
    pattern="$(trigger_value "$f" pattern)"
    path="$(trigger_value "$f" path)"
    strength="$(strength_value "$f")"
    printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
      "${base%.md}" "$tool" "$pattern" "$path" "$strength" "$RULES_DIR/$base"
  done
}

if [ "$MODE" = "check" ]; then
  rc=0
  if [ ! -f "$INDEX_FILE" ]; then
    echo "STALE: $INDEX_FILE missing — run scripts/build-rule-index.sh" >&2
    exit 1
  fi
  tmp="$(mktemp)"
  generate > "$tmp"
  if ! diff -q "$INDEX_FILE" "$tmp" >/dev/null 2>&1; then
    echo "STALE: $INDEX_FILE does not match current rules — run scripts/build-rule-index.sh" >&2
    rc=1
  fi
  rm -f "$tmp"

  tmp2="$(mktemp)"
  generate_triggers > "$tmp2"
  if [ ! -f "$TRIGGERS_FILE" ] || ! diff -q "$TRIGGERS_FILE" "$tmp2" >/dev/null 2>&1; then
    echo "STALE: $TRIGGERS_FILE does not match current rule frontmatter — run scripts/build-rule-index.sh" >&2
    rc=1
  fi
  rm -f "$tmp2"

  [ "$rc" -eq 0 ] && echo "OK: $INDEX_FILE and $TRIGGERS_FILE are up to date"
  exit "$rc"
fi

generate_triggers > "$TRIGGERS_FILE"
n_trig="$(grep -cv '^#' "$TRIGGERS_FILE" || true)"
echo "Wrote $TRIGGERS_FILE ($n_trig triggered rules)"

generate > "$INDEX_FILE"
n_lines="$(wc -l < "$INDEX_FILE" | tr -d ' ')"
echo "Wrote $INDEX_FILE ($n_lines lines, budget $BUDGET_LINES)"
if [ "$n_lines" -gt "$BUDGET_LINES" ]; then
  echo "WARN: wake-up index exceeds budget ($n_lines > $BUDGET_LINES) — consider trimming." >&2
fi
