#!/usr/bin/env bash
set -euo pipefail

# generate-checksums.sh — Release integrity manifest for MTK.
#
# Generates checksums.sha256 at the repo root: one SHA-256 line per file listed
# in .claude/manifest.json (plus the manifest itself and plugin.json), so any
# install can prove its bytes match the published release. mtk-doctor.sh
# verifies it when present.
#
# Usage:
#   bash scripts/generate-checksums.sh                   # (re)generate checksums.sha256
#   bash scripts/generate-checksums.sh --verify          # compare working tree against it
#   bash scripts/generate-checksums.sh --verify --quiet  # summary line only
#   bash scripts/generate-checksums.sh --sign            # also emit checksums.sha256.sig
#
# --sign is opt-in supply-chain hardening: after writing checksums.sha256 it
# signs it with an Ed25519 key so an install can prove WHO published the release,
# not just that the bytes are unmodified. It requires two env vars (both PEM paths):
#   MTK_RELEASE_SIGNING_KEY  — Ed25519 private key, used here to produce the .sig
#   MTK_RELEASE_PUBLIC_KEY   — matching public key, used by mtk-doctor.sh to verify
# If --sign is passed without MTK_RELEASE_SIGNING_KEY, signing is skipped (non-fatal).
# Without --sign, behavior is unchanged and no signature is produced.
# checksums.sha256.sig is a release artifact, tracked like checksums.sha256 itself
# (not gitignored) — only `git add` it as part of an actual release commit; a local
# `--sign` test run for a key you don't intend to ship should not be staged.
#
# Run at release time, after the version bump, as the last change before the
# release commit (S4.11). Mismatches during development are expected; a
# mismatch on a clean install means the bytes are not the released bytes.

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

OUT="checksums.sha256"
SIG="checksums.sha256.sig"
VERIFY=0
QUIET=0
SIGN=0
for arg in "$@"; do
  case "$arg" in
    --verify) VERIFY=1 ;;
    --quiet)  QUIET=1 ;;
    --sign)   SIGN=1 ;;
    -h|--help)
      # Render the full header comment block (first '# ' line down to the first
      # non-comment line) — never slice by absolute line count, it silently
      # truncates when the header grows (see tasks/lessons.md).
      awk '/^# /{f=1} f{ if (!/^#/) exit; sub(/^# ?/, ""); print }' "$0"
      exit 0
      ;;
    *) echo "Unknown arg: $arg" >&2; exit 2 ;;
  esac
done

# Portable SHA-256: coreutils sha256sum (Linux) or shasum -a 256 (macOS base).
if command -v sha256sum >/dev/null 2>&1; then
  hash_tool() { sha256sum "$1"; }
elif command -v shasum >/dev/null 2>&1; then
  hash_tool() { shasum -a 256 "$1"; }
else
  echo "ERROR: neither sha256sum nor shasum found" >&2
  exit 2
fi

# Both tools print "<hash><space><marker><path>", where the marker is a space in text mode
# and '*' in binary mode. Which one you get is a property of the build, not of this script:
# the identical generator wrote '*'-marked lines on one machine and space-marked lines on
# another. That cost real time twice — every regeneration on the other kind of machine
# rewrote all ~350 lines, turning a one-file merge into a whole-file conflict, and --verify
# below could not parse the '*' form at all. Pin the marker so the output is byte-identical
# everywhere.
hash_file() { hash_tool "$1" | sed 's/^\([0-9a-fA-F][0-9a-fA-F]*\) \*/\1  /'; }

[ -f .claude/manifest.json ] || { echo "ERROR: .claude/manifest.json not found — run from a plugin clone" >&2; exit 2; }

# Every file the manifest distributes, plus the manifest and plugin.json
# themselves. The checksum file never lists itself.
list_files() {
  {
    # grep -v '://' drops the manifest's top-level repo-URL "source" field
    grep -oE '"source": *"[^"]+"' .claude/manifest.json | sed 's/.*: *"\(.*\)"/\1/' | grep -v '://'
    echo ".claude/manifest.json"
    echo ".claude-plugin/plugin.json"
  } | grep -vxF "$OUT" | sort -u
}

VERSION="$(grep -o '"version": *"[^"]*"' .claude-plugin/plugin.json | head -1 | sed 's/.*"\([^"]*\)".*/\1/')"

if [ "$VERIFY" -eq 0 ]; then
  MISSING=0
  tmp="$(mktemp)"
  {
    echo "# MTK release checksum manifest v$VERSION"
    echo "# Generated by scripts/generate-checksums.sh — verify with --verify or mtk-doctor.sh"
    while IFS= read -r f; do
      if [ -f "$f" ]; then
        hash_file "$f"
      else
        echo "WARN: manifest lists missing file, skipped: $f" >&2
        MISSING=$((MISSING + 1))
      fi
    done < <(list_files)
  } > "$tmp"
  mv "$tmp" "$OUT"
  COUNT="$(grep -c '^[0-9a-f]' "$OUT")"
  echo "Wrote $OUT — $COUNT files hashed for v$VERSION${MISSING:+ ($MISSING manifest paths missing on disk)}"

  # Optional Ed25519 signature over the checksum manifest (opt-in; see --sign in Usage).
  if [ "$SIGN" -eq 1 ]; then
    if [ -z "${MTK_RELEASE_SIGNING_KEY:-}" ]; then
      echo "--sign requested but MTK_RELEASE_SIGNING_KEY not set — skipping signature" >&2
    elif ! command -v openssl >/dev/null 2>&1; then
      echo "--sign requested but openssl not found — skipping signature" >&2
    else
      openssl pkeyutl -sign -inkey "$MTK_RELEASE_SIGNING_KEY" -rawin -in "$OUT" -out "$SIG"
      echo "Signed $OUT — wrote $SIG (verify with MTK_RELEASE_PUBLIC_KEY via mtk-doctor.sh)"
    fi
  elif [ -f "$SIG" ]; then
    # Regenerating checksums without --sign invalidates any previously shipped
    # signature; left in place it guarantees a false "tampered" verdict downstream.
    echo "WARN: $SIG exists but this run did not re-sign — the signature is now stale; re-run with --sign or remove $SIG" >&2
  fi

  [ "$MISSING" -eq 0 ] || exit 1
else
  [ -f "$OUT" ] || { echo "ERROR: $OUT not found — generate it first" >&2; exit 1; }
  RELVER="$(sed -n 's/^# MTK release checksum manifest v//p' "$OUT" | head -1)"
  TOTAL=0; BAD=0; GONE=0
  while IFS= read -r line; do
    case "$line" in ''|'#'*) continue ;; esac
    expected="${line%% *}"
    # Strip hash, separator, and a binary-mode '*' marker if present. Manifests written
    # before hash_file normalised the marker carry the '*' form; without this the star is
    # read as part of the filename, every entry misses on disk, and the run reports
    # "N checked, 0 mismatched, N missing" — a real exit 1, but for the wrong reason, and
    # it never actually compares a hash.
    file="$(printf '%s' "$line" | sed -e 's/^[0-9a-fA-F]*//' -e 's/^ *//' -e 's/^\*//')"
    TOTAL=$((TOTAL + 1))
    if [ ! -f "$file" ]; then
      GONE=$((GONE + 1))
      [ "$QUIET" -eq 1 ] || echo "MISSING  $file"
    else
      actual="$(hash_file "$file" | awk '{print $1}')"
      if [ "$actual" != "$expected" ]; then
        BAD=$((BAD + 1))
        [ "$QUIET" -eq 1 ] || echo "MISMATCH $file"
      fi
    fi
  done < "$OUT"
  echo "checksums: $TOTAL checked, $BAD mismatched, $GONE missing (release v${RELVER:-?})"
  [ $((BAD + GONE)) -eq 0 ] || exit 1
fi
