#!/usr/bin/env bash
set -euo pipefail

# generate-agents-md.sh — Generate a portable AGENTS.md for cross-agent compatibility
# This file is read by Cursor, GitHub Copilot, Gemini CLI, Codex, and other AI coding tools.
# Run after setup-bootstrap or setup-audit to create/update the cross-agent config.

REFS_DIR=".claude/references"
TECH_STACK_FILE=".claude/tech-stack"

# Marker line written into every generated file. Used to detect whether an
# existing AGENTS.md was produced by this script (safe to overwrite) or is a
# hand-curated routing guide (must not be clobbered).
GEN_MARKER="> Auto-generated by MTK. Sections marked \`## Custom:\` are preserved across regeneration."

FORCE=0
OUTPUT_FILE="AGENTS.md"
while [ $# -gt 0 ]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    -h|--help)
      cat <<'EOF'
Usage: generate-agents-md.sh [--force] [output-file]

Generates AGENTS.md by concatenating .claude/references/*.md so non-Claude-Code
agents (Cursor, Codex, Copilot) can read project conventions in one file.

Safety: refuses to overwrite an existing AGENTS.md unless that file contains
this script's auto-generated marker. Use --force to override (only when you
have backed up the current file or are sure it is disposable). When refusing,
falls back to writing AGENTS.generated.md so the workflow still produces an
artifact.
EOF
      exit 0
      ;;
    --) shift; break ;;
    -*) echo "Unknown flag: $1" >&2; exit 2 ;;
    *)  OUTPUT_FILE="$1"; shift ;;
  esac
done

# Idempotency / safety check: only overwrite files we previously generated.
if [ -f "$OUTPUT_FILE" ] && [ "$FORCE" -ne 1 ]; then
  if ! head -10 "$OUTPUT_FILE" | grep -qF "Auto-generated by MTK"; then
    fallback="${OUTPUT_FILE%.md}.generated.md"
    [ "$fallback" = "$OUTPUT_FILE" ] && fallback="${OUTPUT_FILE}.generated"
    cat >&2 <<EOF
generate-agents-md.sh: refusing to overwrite hand-curated $OUTPUT_FILE.
  Existing file does not carry the script's auto-generated marker.
  Writing to $fallback instead. Use --force to overwrite anyway.
EOF
    OUTPUT_FILE="$fallback"
  fi
fi

# --- Helpers ---

# Strip YAML frontmatter (--- delimited block at top of file) and the first # heading.
# Clean up runs of 3+ blank lines down to 2.
strip_frontmatter_and_title() {
  local file="$1"
  local in_frontmatter=0
  local frontmatter_done=0
  local title_stripped=0

  while IFS= read -r line || [ -n "$line" ]; do
    # Detect frontmatter boundaries
    if [ "$frontmatter_done" -eq 0 ] && [ "$line" = "---" ]; then
      if [ "$in_frontmatter" -eq 0 ]; then
        in_frontmatter=1
        continue
      else
        in_frontmatter=0
        frontmatter_done=1
        continue
      fi
    fi

    # Skip lines inside frontmatter
    if [ "$in_frontmatter" -eq 1 ]; then
      continue
    fi

    # Strip the first # heading (only the very first one after frontmatter)
    if [ "$title_stripped" -eq 0 ]; then
      # Skip leading blank lines before the title
      if [ -z "$line" ]; then
        continue
      fi
      case "$line" in
        "# "*)
          title_stripped=1
          continue
          ;;
        *)
          title_stripped=1
          ;;
      esac
    fi

    printf '%s\n' "$line"
  done < "$file"
}

# Collapse runs of 3+ consecutive blank lines to a single blank line
collapse_blank_lines() {
  awk '
    /^[[:space:]]*$/ { blank++; next }
    { if (blank > 0) print ""; blank = 0; print }
    END { if (blank > 0) print "" }
  '
}

# --- Detect active tech stack ---

stack=""
if [ -f "$TECH_STACK_FILE" ]; then
  stack="$(tr -d '[:space:]' < "$TECH_STACK_FILE")"
fi

# --- Preserve custom sections if AGENTS.md already exists ---

custom_sections=""
if [ -f "$OUTPUT_FILE" ]; then
  custom_sections="$(awk '/^## Custom:/{found=1} found{print}' "$OUTPUT_FILE")" || true
fi

# --- Generate ---

{
  printf '# AGENTS.md\n\n'
  printf '%s\n' "$GEN_MARKER"
  printf '> This file provides project conventions to all AI coding assistants.\n\n'

  # Architecture Principles
  if [ -f "$REFS_DIR/architecture-principles.md" ]; then
    printf '## Architecture Principles\n\n'
    strip_frontmatter_and_title "$REFS_DIR/architecture-principles.md" | collapse_blank_lines
    printf '\n'
  fi

  # Coding Guidelines — emit as pointer, not full body.
  # Inlining 800+ lines of upstream guidelines bloats AGENTS.md with no benefit;
  # consumers can read the referenced file directly when they need the full text.
  if [ -n "$stack" ] && [ -f "$REFS_DIR/${stack}/coding-guidelines.md" ]; then
    printf '## Coding Guidelines (%s)\n\n' "$stack"
    printf 'Full guide: `.claude/references/%s/coding-guidelines.md`.\n' "$stack"
    printf 'Project-specific overrides: `.claude/rules/coding-style.md`.\n\n'
  fi

  # Security Requirements
  if [ -f "$REFS_DIR/security-checklist.md" ]; then
    printf '## Security Requirements\n\n'
    strip_frontmatter_and_title "$REFS_DIR/security-checklist.md" | collapse_blank_lines
    printf '\n'
  fi

  # Testing Expectations
  if [ -f "$REFS_DIR/testing-patterns.md" ]; then
    printf '## Testing Expectations\n\n'
    strip_frontmatter_and_title "$REFS_DIR/testing-patterns.md" | collapse_blank_lines
    printf '\n'
  fi

  # Performance Guidelines
  if [ -f "$REFS_DIR/performance-checklist.md" ]; then
    printf '## Performance Guidelines\n\n'
    strip_frontmatter_and_title "$REFS_DIR/performance-checklist.md" | collapse_blank_lines
    printf '\n'
  fi

  # Stack-specific supplements (if they exist)
  if [ -n "$stack" ] && [ -d "$REFS_DIR/${stack}" ]; then
    for supplement in "$REFS_DIR/${stack}/"*.md; do
      [ -f "$supplement" ] || continue
      basename_file="$(basename "$supplement")"
      # Skip coding-guidelines — already included above
      [ "$basename_file" = "coding-guidelines.md" ] && continue
      # Derive a section name from the filename
      section_name="$(echo "$basename_file" | sed 's/\.md$//' | sed 's/-/ /g')"
      # Capitalize each word (portable: use sed, not \u which is GNU-only)
      section_name="$(echo "$section_name" | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)} 1')"
      # Capitalize stack name for display
      display_stack="$(echo "$stack" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')"
      printf '## %s — %s\n\n' "$display_stack" "$section_name"
      strip_frontmatter_and_title "$supplement" | collapse_blank_lines
      printf '\n'
    done
  fi

  # Domain supplement (if present)
  if [ -f "$REFS_DIR/domain-finance.md" ]; then
    printf '## Domain — Finance\n\n'
    strip_frontmatter_and_title "$REFS_DIR/domain-finance.md" | collapse_blank_lines
    printf '\n'
  fi

  # Append preserved custom sections
  if [ -n "$custom_sections" ]; then
    printf '%s\n' "$custom_sections"
  fi

} > "$OUTPUT_FILE"

line_count="$(wc -l < "$OUTPUT_FILE" | tr -d ' ')"
echo "Generated $OUTPUT_FILE ($line_count lines)"
