#!/usr/bin/env bash
set -euo pipefail

# generate-tool-configs.sh — Generate native config files for non-Claude AI coding tools
#
# Generates project guidelines in each tool's native format, using the same
# reference files that power AGENTS.md. Content is read-only — regenerate
# with this script, don't hand-edit.
#
# Formats:
#   cursor-rules   .cursor/rules/mtk-*.mdc  (glob-scoped Cursor rules)
#   copilot         .github/copilot-instructions.md
#   windsurf        .windsurfrules
#   gemini          GEMINI.md
#   cline           .clinerules
#
# Safety: every file this script writes carries a "GEN_MARKER_TEXT" marker
# (see below). If an output path already exists and does NOT carry that
# marker, it is treated as hand-curated and left untouched — a one-line
# warning is printed and the script moves on to the next output. Pass
# --force to overwrite hand-curated files anyway. Mirrors the guard in
# generate-agents-md.sh (duplicated independently; these are standalone
# scripts).
#
# Usage:
#   bash scripts/generate-tool-configs.sh --all
#   bash scripts/generate-tool-configs.sh --format cursor-rules
#   bash scripts/generate-tool-configs.sh --format copilot --format windsurf
#   bash scripts/generate-tool-configs.sh --all --force

REFS_DIR=".claude/references"
# In a marketplace install, manifest lives in the plugin root; in a local clone,
# it lives at the repo root. Prefer project-local; fall back to plugin root.
if [ -f ".claude/manifest.json" ]; then
  MANIFEST=".claude/manifest.json"
elif [ -n "${CLAUDE_PLUGIN_ROOT:-}" ] && [ -f "${CLAUDE_PLUGIN_ROOT}/.claude/manifest.json" ]; then
  MANIFEST="${CLAUDE_PLUGIN_ROOT}/.claude/manifest.json"
else
  MANIFEST=".claude/manifest.json"  # let downstream fail with a clear missing-file error
fi
TECH_STACK_FILE=".claude/tech-stack"

FORCE=0

# Marker substring written into every file this script generates (flat-file
# outputs and per-file .mdc outputs alike). Used to detect whether an
# existing output was produced by this script (safe to overwrite) or is
# hand-curated (must not be clobbered without --force).
GEN_MARKER_TEXT="Auto-generated by MTK"

# ─── Helpers ───────────────────────────────────────────────────────────────────

# Idempotency / safety check: refuse to overwrite an existing output file
# unless it carries GEN_MARKER_TEXT (i.e. this script produced it) or --force
# was passed. Prints a one-line warning and returns 1 on refusal — callers
# must skip that single write and continue with the rest of the run, never
# abort. Mirrors generate-agents-md.sh's guard for AGENTS.md.
check_overwrite_allowed() {
  local target="$1"
  [ -f "$target" ] || return 0
  [ "$FORCE" -eq 1 ] && return 0
  if head -10 "$target" | grep -qF "$GEN_MARKER_TEXT"; then
    return 0
  fi
  echo "generate-tool-configs.sh: refusing to overwrite hand-curated $target (no auto-generated marker found; use --force to override)." >&2
  return 1
}

# Strip YAML frontmatter and the first # heading. Shared with generate-agents-md.sh.
strip_frontmatter_and_title() {
  local file="$1"
  local in_frontmatter=0
  local frontmatter_done=0
  local title_stripped=0

  while IFS= read -r line || [ -n "$line" ]; do
    if [ "$frontmatter_done" -eq 0 ] && [ "$line" = "---" ]; then
      if [ "$in_frontmatter" -eq 0 ]; then
        in_frontmatter=1; continue
      else
        in_frontmatter=0; frontmatter_done=1; continue
      fi
    fi
    [ "$in_frontmatter" -eq 1 ] && continue
    if [ "$title_stripped" -eq 0 ]; then
      [ -z "$line" ] && continue
      case "$line" in "# "*) title_stripped=1; continue ;; *) title_stripped=1 ;; esac
    fi
    printf '%s\n' "$line"
  done < "$file"
}

# Collapse runs of 3+ consecutive blank lines to one blank line.
collapse_blank_lines() {
  awk '
    /^[[:space:]]*$/ { blank++; next }
    { if (blank > 0) print ""; blank = 0; print }
    END { if (blank > 0) print "" }
  '
}

# Extract the BODY of the first "## Critical Rules" section (prefix match, so
# "## Critical Rules" and "## Critical Rules (Always Apply)" both match) from a
# CLAUDE.md-style file. The matched heading itself is NOT emitted — every caller
# prints its own "## Critical Rules (from CLAUDE.md)" heading, and re-emitting
# the source heading produced two stacked duplicate H2s in generated configs.
# Warns on stderr (non-fatal) when the file exists but no heading matched, so a
# renamed heading does not silently drop the rules from every generated config.
# Duplicated verbatim in generate-agents-md.sh (standalone scripts).
extract_critical_rules() {
  local file="$1" body
  [ -f "$file" ] || return 0
  body="$(awk '
    /^## Critical Rules/ && !started { started=1; next }
    started && /^## / { exit }
    started && n == 0 && /^[[:space:]]*$/ { next }
    started { lines[++n] = $0; next }
    END {
      # Trim trailing blank lines and horizontal rules (e.g. "---") so the
      # extracted section does not end with a stray markdown separator.
      while (n > 0 && (lines[n] ~ /^[[:space:]]*$/ || lines[n] ~ /^-{3,}[[:space:]]*$/)) n--
      for (i = 1; i <= n; i++) print lines[i]
    }
  ' "$file")"
  if [ -n "$body" ]; then
    printf '%s\n' "$body"
  else
    echo "NOTE: no '## Critical Rules' heading found in $file — generated configs will omit critical rules" >&2
  fi
}

# Extract applyTo globs for a manifest target path.
# Outputs comma-separated quoted strings, e.g.: "**/*DbContext*", "**/Entities/**"
# Returns empty string if no applyTo found.
extract_apply_to() {
  local target="$1"
  [ -f "$MANIFEST" ] || return 0
  awk -v target="$target" '
    BEGIN { found=0; in_apply=0 }
    index($0, "\"" target "\"") > 0 && /\"target\"/ { found=1; next }
    found && /\"applyTo\"/ { in_apply=1; next }
    in_apply && /\]/ { exit }
    in_apply {
      gsub(/^[[:space:]]+/, "")
      gsub(/,$/, "")
      if ($0 ~ /^"/) printf "%s, ", $0
    }
    found && !in_apply && /^\s*\}/ { found=0 }
  ' "$MANIFEST" | sed 's/, $//'
}

# ─── Detect tech stack ─────────────────────────────────────────────────────────

stack=""
if [ -f "$TECH_STACK_FILE" ]; then
  stack="$(tr -d '[:space:]' < "$TECH_STACK_FILE")"
fi

# ─── Content assembly ──────────────────────────────────────────────────────────

# Emit a single reference file as a markdown section.
emit_section() {
  local title="$1" file="$2"
  [ -f "$file" ] || return 0
  printf '## %s\n\n' "$title"
  strip_frontmatter_and_title "$file" | collapse_blank_lines
  printf '\n\n'
}

# Assemble all reference content into a single stream (for flat-file formats).
assemble_all_content() {
  # Critical Rules — pulled from the project's CLAUDE.md. Highest-value content
  # for tools with no hook enforcement, so it leads the file. Skipped silently
  # if CLAUDE.md has no matching heading.
  if [ -f "CLAUDE.md" ]; then
    local critical_rules
    critical_rules="$(extract_critical_rules "CLAUDE.md")"
    if [ -n "$critical_rules" ]; then
      printf '## Critical Rules (from CLAUDE.md)\n\n'
      printf '%s\n' "$critical_rules" | collapse_blank_lines
      printf '\n\n'
    fi
  fi

  # Architecture principles
  emit_section "Architecture Principles" "$REFS_DIR/architecture-principles.md"

  # Coding guidelines — emit as pointer, not full body.
  # Full upstream guidelines can be 800+ lines; inlining them into copilot-instructions.md
  # (read on every Copilot request) wastes context. Tools that need the full text read
  # the referenced file directly.
  if [ -n "$stack" ] && [ -f "$REFS_DIR/${stack}/coding-guidelines.md" ]; then
    local display_stack
    display_stack="$(echo "$stack" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')"
    printf '## Coding Guidelines (%s)\n\n' "$display_stack"
    printf 'Full guide: `.claude/references/%s/coding-guidelines.md`.\n' "$stack"
    printf 'Project-specific overrides: `.claude/rules/coding-style.md`.\n\n'
  fi

  # Core references
  emit_section "Security Requirements" "$REFS_DIR/security-checklist.md"
  emit_section "Testing Expectations" "$REFS_DIR/testing-patterns.md"
  emit_section "Performance Guidelines" "$REFS_DIR/performance-checklist.md"

  # Stack-specific supplements
  if [ -n "$stack" ] && [ -d "$REFS_DIR/${stack}" ]; then
    local display_stack
    display_stack="$(echo "$stack" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')"
    for supplement in "$REFS_DIR/${stack}/"*.md; do
      [ -f "$supplement" ] || continue
      local basename_file
      basename_file="$(basename "$supplement")"
      [ "$basename_file" = "coding-guidelines.md" ] && continue
      [ "$basename_file" = "analyzer-config.md" ] && continue
      local section_name
      section_name="$(echo "$basename_file" | sed 's/\.md$//' | sed 's/-/ /g')"
      section_name="$(echo "$section_name" | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)} 1')"
      emit_section "$display_stack — $section_name" "$supplement"
    done
  fi

  # Domain supplements
  for domain_file in "$REFS_DIR"/domain-*.md; do
    [ -f "$domain_file" ] || continue
    local domain_name
    domain_name="$(basename "$domain_file" | sed 's/^domain-//' | sed 's/\.md$//')"
    local display_domain
    display_domain="$(echo "$domain_name" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')"
    emit_section "Domain — $display_domain" "$domain_file"
  done
}

# ─── Format: Cursor MDC Rules ─────────────────────────────────────────────────
# Each reference becomes a .cursor/rules/mtk-*.mdc file with frontmatter.
# Files with applyTo globs get glob-scoped rules; others get alwaysApply: true.

write_mdc() {
  local file="$1" output="$2" description="$3" globs="${4:-}"
  check_overwrite_allowed "$output" || return 0
  {
    printf -- '---\n'
    printf 'description: %s\n' "$description"
    if [ -n "$globs" ]; then
      printf 'globs: [%s]\n' "$globs"
      printf 'alwaysApply: false\n'
    else
      printf 'alwaysApply: true\n'
    fi
    printf -- '---\n\n'
    printf '<!-- Auto-generated by MTK. Regenerate with: `bash scripts/generate-tool-configs.sh --format cursor-rules` -->\n\n'
    strip_frontmatter_and_title "$file" | collapse_blank_lines
  } > "$output"
}

generate_cursor_rules() {
  mkdir -p .cursor/rules

  # Remove stale MTK-generated rules (only mtk-* prefixed files), but only
  # ones that still carry our marker — a hand-curated file that happens to
  # share an mtk-* filename is left alone (not deleted) so a later write to
  # that same path goes through check_overwrite_allowed, which is the single
  # place a preserved-file warning is printed. Under --force, remove all of
  # them unconditionally (matches --force's overwrite-anything contract).
  for f in .cursor/rules/mtk-*.mdc; do
    [ -f "$f" ] || continue
    if [ "$FORCE" -eq 1 ] || grep -qF "$GEN_MARKER_TEXT" "$f"; then
      rm -f "$f"
    fi
  done

  # Always-apply: Critical Rules from the project's CLAUDE.md. Highest-value
  # content for a tool with no hook enforcement. Skipped silently if CLAUDE.md
  # has no matching heading.
  if [ -f "CLAUDE.md" ]; then
    local critical_rules
    critical_rules="$(extract_critical_rules "CLAUDE.md")"
    if [ -n "$critical_rules" ] && check_overwrite_allowed ".cursor/rules/mtk-critical-rules.mdc"; then
      {
        printf -- '---\n'
        printf 'description: %s\n' "Critical rules from CLAUDE.md — always apply"
        printf 'alwaysApply: true\n'
        printf -- '---\n\n'
        printf '<!-- Auto-generated by MTK. Regenerate with: `bash scripts/generate-tool-configs.sh --format cursor-rules` -->\n\n'
        printf '## Critical Rules (from CLAUDE.md)\n\n'
        printf '%s\n' "$critical_rules" | collapse_blank_lines
      } > ".cursor/rules/mtk-critical-rules.mdc"
    fi
  fi

  # Always-apply: architecture principles
  if [ -f "$REFS_DIR/architecture-principles.md" ]; then
    write_mdc "$REFS_DIR/architecture-principles.md" \
      ".cursor/rules/mtk-architecture.mdc" \
      "Architecture principles for this codebase"
  fi

  # Always-apply: coding guidelines
  if [ -n "$stack" ] && [ -f "$REFS_DIR/${stack}/coding-guidelines.md" ]; then
    write_mdc "$REFS_DIR/${stack}/coding-guidelines.md" \
      ".cursor/rules/mtk-coding-guidelines.mdc" \
      "$stack coding guidelines and conventions"
  fi

  # Always-apply: security checklist
  if [ -f "$REFS_DIR/security-checklist.md" ]; then
    write_mdc "$REFS_DIR/security-checklist.md" \
      ".cursor/rules/mtk-security.mdc" \
      "Security checklist — auth, secrets, PII, SQL injection"
  fi

  # Glob-scoped: testing patterns
  if [ -f "$REFS_DIR/testing-patterns.md" ]; then
    local globs
    globs="$(extract_apply_to ".claude/references/testing-patterns.md")"
    [ -z "$globs" ] && globs='"**/tests/**", "**/*.test.*", "**/*.spec.*", "**/*Test*"'
    write_mdc "$REFS_DIR/testing-patterns.md" \
      ".cursor/rules/mtk-testing.mdc" \
      "Testing patterns and conventions" \
      "$globs"
  fi

  # On-demand: performance checklist (no globs — manually loaded)
  if [ -f "$REFS_DIR/performance-checklist.md" ]; then
    write_mdc "$REFS_DIR/performance-checklist.md" \
      ".cursor/rules/mtk-performance.mdc" \
      "Performance checklist — load when optimizing"
  fi

  # Stack-specific supplements with applyTo globs
  if [ -n "$stack" ] && [ -d "$REFS_DIR/${stack}" ]; then
    for supplement in "$REFS_DIR/${stack}/"*.md; do
      [ -f "$supplement" ] || continue
      local basename_file
      basename_file="$(basename "$supplement")"
      [ "$basename_file" = "coding-guidelines.md" ] && continue
      [ "$basename_file" = "analyzer-config.md" ] && continue

      local rule_name section_name target_path globs
      rule_name="$(echo "$basename_file" | sed 's/\.md$//')"
      section_name="$(echo "$rule_name" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)} 1')"
      target_path=".claude/references/${stack}/${basename_file}"
      globs="$(extract_apply_to "$target_path")"

      if [ -n "$globs" ]; then
        write_mdc "$supplement" \
          ".cursor/rules/mtk-${stack}-${rule_name}.mdc" \
          "$stack — $section_name" \
          "$globs"
      else
        write_mdc "$supplement" \
          ".cursor/rules/mtk-${stack}-${rule_name}.mdc" \
          "$stack — $section_name"
      fi
    done
  fi

  # Domain supplements (always-apply)
  for domain_file in "$REFS_DIR"/domain-*.md; do
    [ -f "$domain_file" ] || continue
    local domain_name display_domain
    domain_name="$(basename "$domain_file" | sed 's/^domain-//' | sed 's/\.md$//')"
    display_domain="$(echo "$domain_name" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')"
    write_mdc "$domain_file" \
      ".cursor/rules/mtk-domain-${domain_name}.mdc" \
      "$display_domain domain rules"
  done

  local count
  count=$(find .cursor/rules -name "mtk-*.mdc" 2>/dev/null | wc -l | tr -d ' ')
  echo "Generated $count Cursor rule files in .cursor/rules/"
}

# ─── Format: Single-file generators ───────────────────────────────────────────

generate_single_file() {
  local format="$1" output="$2" title="$3"
  check_overwrite_allowed "$output" || return 0
  {
    printf '# %s\n\n' "$title"
    printf '> Auto-generated by MTK. Regenerate with: `bash scripts/generate-tool-configs.sh --format %s`\n\n' "$format"
    assemble_all_content
  } | collapse_blank_lines > "$output"
  local lines
  lines=$(wc -l < "$output" | tr -d ' ')
  echo "Generated $output ($lines lines)"
}

generate_copilot() {
  mkdir -p .github
  generate_single_file "copilot" ".github/copilot-instructions.md" "Copilot Instructions"
}

generate_windsurf() {
  generate_single_file "windsurf" ".windsurfrules" "Windsurf Rules"
}

generate_gemini() {
  generate_single_file "gemini" "GEMINI.md" "Project Guidelines"
}

generate_cline() {
  generate_single_file "cline" ".clinerules" "Project Rules"
}

# ─── CLI ───────────────────────────────────────────────────────────────────────

usage() {
  echo "Usage: $0 [--all | --format <cursor-rules|copilot|windsurf|gemini|cline> ...] [--force]" >&2
  exit 1
}

formats=()
while [ $# -gt 0 ]; do
  case "$1" in
    --all)
      # If the project pins a format list in .claude/tool-configs.conf,
      # honor it; otherwise generate every supported format.
      if [ -f .claude/tool-configs.conf ]; then
        while IFS= read -r line || [ -n "$line" ]; do
          line="${line%%#*}"; line="$(echo "$line" | tr -d '[:space:]')"
          [ -n "$line" ] && formats+=("$line")
        done < .claude/tool-configs.conf
      else
        formats=(cursor-rules copilot windsurf gemini cline)
      fi
      shift
      ;;
    --format)       [ $# -ge 2 ] || usage; formats+=("$2"); shift 2 ;;
    --force)        FORCE=1; shift ;;
    -h|--help)      usage ;;
    *)              usage ;;
  esac
done

[ ${#formats[@]} -eq 0 ] && usage

for fmt in "${formats[@]}"; do
  case "$fmt" in
    cursor-rules) generate_cursor_rules ;;
    copilot)      generate_copilot ;;
    windsurf)     generate_windsurf ;;
    gemini)       generate_gemini ;;
    cline)        generate_cline ;;
    *)            echo "Unknown format: $fmt" >&2; exit 1 ;;
  esac
done
