#!/usr/bin/env bash
set -euo pipefail

# generate-checksums.sh — Release integrity manifest for MTK.
#
# Generates checksums.sha256 at the repo root: one SHA-256 line per file listed
# in .claude/manifest.json (plus the manifest itself and plugin.json), so any
# install can prove its bytes match the published release. mtk-doctor.sh
# verifies it when present.
#
# Usage:
#   bash scripts/generate-checksums.sh                   # (re)generate checksums.sha256
#   bash scripts/generate-checksums.sh --verify          # compare working tree against it
#   bash scripts/generate-checksums.sh --verify --quiet  # summary line only
#
# Run at release time, after the version bump, as the last change before the
# release commit (S4.11). Mismatches during development are expected; a
# mismatch on a clean install means the bytes are not the released bytes.

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

OUT="checksums.sha256"
VERIFY=0
QUIET=0
for arg in "$@"; do
  case "$arg" in
    --verify) VERIFY=1 ;;
    --quiet)  QUIET=1 ;;
    -h|--help)
      grep '^# ' "$0" | head -16 | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "Unknown arg: $arg" >&2; exit 2 ;;
  esac
done

# Portable SHA-256: coreutils sha256sum (Linux) or shasum -a 256 (macOS base).
if command -v sha256sum >/dev/null 2>&1; then
  hash_file() { sha256sum "$1"; }
elif command -v shasum >/dev/null 2>&1; then
  hash_file() { shasum -a 256 "$1"; }
else
  echo "ERROR: neither sha256sum nor shasum found" >&2
  exit 2
fi

[ -f .claude/manifest.json ] || { echo "ERROR: .claude/manifest.json not found — run from a plugin clone" >&2; exit 2; }

# Every file the manifest distributes, plus the manifest and plugin.json
# themselves. The checksum file never lists itself.
list_files() {
  {
    # grep -v '://' drops the manifest's top-level repo-URL "source" field
    grep -oE '"source": *"[^"]+"' .claude/manifest.json | sed 's/.*: *"\(.*\)"/\1/' | grep -v '://'
    echo ".claude/manifest.json"
    echo ".claude-plugin/plugin.json"
  } | grep -vxF "$OUT" | sort -u
}

VERSION="$(grep -o '"version": *"[^"]*"' .claude-plugin/plugin.json | head -1 | sed 's/.*"\([^"]*\)".*/\1/')"

if [ "$VERIFY" -eq 0 ]; then
  MISSING=0
  tmp="$(mktemp)"
  {
    echo "# MTK release checksum manifest v$VERSION"
    echo "# Generated by scripts/generate-checksums.sh — verify with --verify or mtk-doctor.sh"
    while IFS= read -r f; do
      if [ -f "$f" ]; then
        hash_file "$f"
      else
        echo "WARN: manifest lists missing file, skipped: $f" >&2
        MISSING=$((MISSING + 1))
      fi
    done < <(list_files)
  } > "$tmp"
  mv "$tmp" "$OUT"
  COUNT="$(grep -c '^[0-9a-f]' "$OUT")"
  echo "Wrote $OUT — $COUNT files hashed for v$VERSION${MISSING:+ ($MISSING manifest paths missing on disk)}"
  [ "$MISSING" -eq 0 ] || exit 1
else
  [ -f "$OUT" ] || { echo "ERROR: $OUT not found — generate it first" >&2; exit 1; }
  RELVER="$(sed -n 's/^# MTK release checksum manifest v//p' "$OUT" | head -1)"
  TOTAL=0; BAD=0; GONE=0
  while IFS= read -r line; do
    case "$line" in ''|'#'*) continue ;; esac
    expected="${line%% *}"
    file="$(printf '%s' "$line" | sed 's/^[0-9a-fA-F]* *//')"
    TOTAL=$((TOTAL + 1))
    if [ ! -f "$file" ]; then
      GONE=$((GONE + 1))
      [ "$QUIET" -eq 1 ] || echo "MISSING  $file"
    else
      actual="$(hash_file "$file" | awk '{print $1}')"
      if [ "$actual" != "$expected" ]; then
        BAD=$((BAD + 1))
        [ "$QUIET" -eq 1 ] || echo "MISMATCH $file"
      fi
    fi
  done < "$OUT"
  echo "checksums: $TOTAL checked, $BAD mismatched, $GONE missing (release v${RELVER:-?})"
  [ $((BAD + GONE)) -eq 0 ] || exit 1
fi
