#!/usr/bin/env bash
set -euo pipefail

# resolve-constitution.sh — resolve which file is this repo's agent constitution.
#
# The third sibling of resolve-tech-stack.sh and resolve-artifact-root.sh, and
# deliberately the same shape: one standalone resolver owns one question, every
# caller shells out to it, and `--explain` says why.
#
# Before this script the predicate below was copy-pasted into nine callers
# (constitution-digest, generate-agents-md, generate-tool-configs,
# rule-enforcement-map, setup-refresh-plan, repo-health-score, mtk-doctor,
# mtk-savings, and a Python transcription in build-context-pack). They had
# already diverged — different marker handling, different stderr redirection,
# different empty-repo answers — and a symlink hole had to be patched into all
# nine by hand. One rule, one file, one test matrix.
#
# THE RULE (canonical mode). AGENTS.md is the constitution when:
#   1. AGENTS.md exists, AND
#   2. it is NOT generator-marked — the string `Auto-generated by MTK` does not
#      appear in its first 10 lines. A marked AGENTS.md is the legacy references
#      SUMMARY that generate-agents-md.sh / generate-tool-configs.sh write, never
#      a constitution, so it must never be promoted over a real CLAUDE.md, AND
#   3. CLAUDE.md is absent, OR is the very same file (a `CLAUDE.md -> AGENTS.md`
#      symlink cannot be a shim *for* AGENTS.md; before this clause that case
#      resolved to CLAUDE.md and let `generate-agents-md.sh --force` overwrite a
#      hand-authored constitution with a generated summary), OR contains a line
#      matching `^@AGENTS\.md` (an explicit shim import).
# Otherwise: CLAUDE.md. A legacy repo resolves exactly as it did before the
# AGENTS.md inversion.
#
# --loaded is a DIFFERENT question: "which constitution actually costs always-on
# context in Claude Code?" That is the canonical rule MINUS the generator-marker
# clause, because Claude Code's default `claude-md-or-agents-md` mode reads
# CLAUDE.md when present and ignores AGENTS.md entirely — regardless of how
# AGENTS.md was produced. Used by mtk-savings.sh and mtk-doctor.sh for context
# accounting. Prints an empty line when no constitution is loaded at all.
#
# Prints the resolved path to stdout (prefixed by the target dir when one is
# given). `--explain` prints the reason to stderr. Exit 0 always — a repo with
# no constitution at all still answers `CLAUDE.md` in canonical mode (the
# conventional destination), and empty in --loaded mode. Callers that care
# whether the file EXISTS must test for it: the resolver answers "which file",
# not "is there one".
#
# Usage:
#   bash scripts/resolve-constitution.sh [--explain] [--loaded] [target-dir]
#
# No dependencies beyond coreutils (S3.3) — awk + grep only, no git.
#
# The marker is matched on a CAPTURED variable, never piped into `grep -q`:
# grep exits on first match, awk takes SIGPIPE, and `set -o pipefail` would turn
# that into a spurious failure (S3.17).

explain=0
loaded=0
target=""
while [ $# -gt 0 ]; do
  case "$1" in
    --explain) explain=1; shift ;;
    --loaded)  loaded=1; shift ;;
    -h|--help)
      sed -n '3,50p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    --) shift; break ;;
    -*) echo "resolve-constitution: unknown flag: $1" >&2; exit 2 ;;
    *)  target="$1"; shift ;;
  esac
done

# Normalise the target into a prefix that is either empty (cwd-relative, which
# is what every caller but constitution-digest.sh wants) or `dir/`.
prefix=""
if [ -n "$target" ]; then
  case "$target" in
    */) prefix="$target" ;;
    *)  prefix="$target/" ;;
  esac
fi

agents="${prefix}AGENTS.md"
claude="${prefix}CLAUDE.md"

_emit() {
  [ "$explain" -eq 1 ] && printf 'resolve-constitution: %s (%s)\n' "$1" "$2" >&2
  printf '%s\n' "$1"
  exit 0
}

marked=0
if [ -f "$agents" ]; then
  head10="$(awk 'NR<=10' "$agents" 2>/dev/null || true)"
  case "$head10" in *"Auto-generated by MTK"*) marked=1 ;; esac
fi

if [ "$loaded" -eq 1 ]; then
  # Context-accounting mode: the generator marker is irrelevant — Claude Code
  # reads CLAUDE.md when it exists and ignores AGENTS.md unless CLAUDE.md
  # imports it.
  if [ -f "$claude" ]; then
    if [ -f "$agents" ] && { [ "$claude" -ef "$agents" ] || grep -qE '^@AGENTS\.md' "$claude" 2>/dev/null; }; then
      _emit "$agents" "CLAUDE.md is a shim importing AGENTS.md — AGENTS.md is what loads"
    fi
    _emit "$claude" "CLAUDE.md present and not a shim — it suppresses AGENTS.md in the default claude-md-or-agents-md mode"
  fi
  if [ -f "$agents" ]; then
    _emit "$agents" "no CLAUDE.md — AGENTS.md loads directly"
  fi
  [ "$explain" -eq 1 ] && printf 'resolve-constitution: (none) (no constitution file in %s)\n' "${prefix:-.}" >&2
  printf '\n'
  exit 0
fi

# Canonical mode.
if [ -f "$agents" ] && [ "$marked" -eq 0 ]; then
  if [ ! -f "$claude" ]; then
    _emit "$agents" "AGENTS.md present, not generator-marked, no CLAUDE.md"
  fi
  if [ "$claude" -ef "$agents" ]; then
    _emit "$agents" "CLAUDE.md is the same file as AGENTS.md (symlink) — it cannot be a shim for it"
  fi
  if grep -qE '^@AGENTS\.md' "$claude" 2>/dev/null; then
    _emit "$agents" "CLAUDE.md is a shim importing AGENTS.md"
  fi
  _emit "$claude" "AGENTS.md exists but CLAUDE.md is a real constitution, not a shim"
fi

if [ -f "$agents" ] && [ "$marked" -eq 1 ]; then
  _emit "$claude" "AGENTS.md is generator-marked (a references summary, not a constitution)"
fi

_emit "$claude" "no AGENTS.md"
