#!/usr/bin/env bash
set -euo pipefail

# spec-archive.sh — Sync a feature spec (delta) back into its area baseline and
# append an audit record (archive-merges-back model).
#
# Run ONLY after spec-drift-detection returns a clean PASS. See
# .claude/references/delta-spec-model.md for the model.
#
# Usage:
#   bash scripts/spec-archive.sh <spec.json> [--verdict PASS] [--at <ISO8601>]
#
#   --verdict   drift verdict to record (default PASS). Refuses non-PASS.
#   --at        timestamp to stamp (default: `date -u`). Lets callers pin time.
#
# Idempotent: re-archiving the same slug for the same area is a no-op.

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

command -v jq >/dev/null || { echo "ERROR: jq is required" >&2; exit 2; }

SPEC_JSON="${1:-}"
[ -n "$SPEC_JSON" ] || { echo "Usage: spec-archive.sh <spec.json> [--verdict PASS] [--at <ISO8601>]" >&2; exit 2; }
[ -f "$SPEC_JSON" ] || { echo "ERROR: spec sidecar not found: $SPEC_JSON" >&2; exit 2; }
shift

VERDICT="PASS"
STAMP=""
while [ $# -gt 0 ]; do
  case "$1" in
    --verdict) VERDICT="${2:-}"; shift 2 ;;
    --at)      STAMP="${2:-}"; shift 2 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done
[ -n "$STAMP" ] || STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

if [ "$VERDICT" != "PASS" ]; then
  echo "REFUSED: drift verdict is '$VERDICT', not PASS. Fix drift before archiving." >&2
  exit 1
fi

AREA="$(jq -r '.baseline_area // empty' "$SPEC_JSON")"
SLUG="$(jq -r '.slug // empty' "$SPEC_JSON")"
DATE="$(jq -r '.date // empty' "$SPEC_JSON")"
[ -n "$AREA" ] || { echo "ERROR: spec has no baseline_area — cannot archive. Add it to the sidecar." >&2; exit 1; }
[ -n "$SLUG" ] || { echo "ERROR: spec has no slug." >&2; exit 1; }

BASE_DIR="docs/specs/baseline"
BASE_JSON="$BASE_DIR/$AREA.json"
BASE_MD="$BASE_DIR/$AREA.md"
AUDIT="$BASE_DIR/$AREA.audit.jsonl"
mkdir -p "$BASE_DIR"

# Idempotency: already archived this slug? Match exact slug values in the audit
# trail with jq (not grep) so a slug containing regex/substring metachars cannot
# falsely match a different slug and silently drop this archive.
if [ -f "$AUDIT" ] && jq -e --arg s "$SLUG" 'select(.slug == $s)' "$AUDIT" >/dev/null 2>&1; then
  echo "NO-OP: '$SLUG' already archived to baseline '$AREA'."
  exit 0
fi

# Seed an empty baseline if absent.
if [ ! -f "$BASE_JSON" ]; then
  echo "{\"area\":\"$AREA\",\"contracts\":{},\"files\":{},\"history\":[]}" | jq . > "$BASE_JSON"
fi

tmp="$(mktemp)"

# Merge: fold public_contracts and change_manifest into the baseline maps,
# keyed by signature / path. Then apply explicit delta.removes.
jq \
  --arg slug "$SLUG" \
  --arg date "$DATE" \
  --arg verdict "$VERDICT" \
  --arg at "$STAMP" \
  --slurpfile spec "$SPEC_JSON" \
'
  ($spec[0]) as $s
  | .contracts as $c0
  | .files as $f0
  # contracts keyed by signature
  | .contracts = (reduce ($s.public_contracts // [])[] as $pc ($c0;
      .[$pc.signature] = { kind: ($pc.kind // "?"), change: ($pc.change // "?"),
                           source_slug: $slug, date: $date }))
  # files keyed by path
  | .files = (reduce ($s.change_manifest // [])[] as $fm ($f0;
      .[$fm.path] = { action: ($fm.action // "?"), purpose: ($fm.purpose // ""),
                      source_slug: $slug }))
  # explicit removes drop keys from both maps
  | .contracts = (reduce (($s.delta.removes) // [])[] as $r (.contracts; del(.[$r])))
  | .files     = (reduce (($s.delta.removes) // [])[] as $r (.files;     del(.[$r])))
  | .history += [ { slug: $slug, date: $date, verdict: $verdict, archived_at: $at } ]
' "$BASE_JSON" > "$tmp"
mv "$tmp" "$BASE_JSON"

# Append audit record (compact one-liner).
adds="$(jq -c '[(.change_manifest // [])[].path] + [(.public_contracts // [])[].signature]' "$SPEC_JSON")"
removes="$(jq -c '(.delta.removes) // []' "$SPEC_JSON")"
printf '{"slug":"%s","date":"%s","verdict":"%s","archived_at":"%s","adds":%s,"removes":%s}\n' \
  "$SLUG" "$DATE" "$VERDICT" "$STAMP" "$adds" "$removes" >> "$AUDIT"

# Regenerate the human-readable baseline view.
{
  echo "# Baseline — $AREA"
  echo
  echo "> GENERATED by \`scripts/spec-archive.sh\` — do not edit by hand."
  echo "> Edit the feature spec and re-archive to change this."
  echo
  echo "## Public contracts"
  echo
  echo "| Signature | Kind | Last change | Source slug |"
  echo "|---|---|---|---|"
  jq -r '.contracts | to_entries[] | "| \(.key) | \(.value.kind) | \(.value.change) | \(.value.source_slug) |"' "$BASE_JSON" | sort
  echo
  echo "## Files"
  echo
  echo "| Path | Action | Source slug | Purpose |"
  echo "|---|---|---|---|"
  jq -r '.files | to_entries[] | "| \(.key) | \(.value.action) | \(.value.source_slug) | \(.value.purpose) |"' "$BASE_JSON" | sort
  echo
  echo "## Archive history"
  echo
  jq -r '.history[] | "- \(.date) · \(.slug) · drift \(.verdict) · archived \(.archived_at)"' "$BASE_JSON"
} > "$BASE_MD"

# Fold newly shipped public contracts into the repo's capability index, if one
# exists — completed deltas become living documentation, not just an audit
# trail. Append-only (shrink-guard exempt per S3.16); idempotent via slug marker.
CODE_INDEX="CODE_INDEX.md"
if [ -f "$CODE_INDEX" ] && ! grep -qF "spec $SLUG" "$CODE_INDEX" 2>/dev/null; then
  NEW_CONTRACTS="$(jq -r '(.public_contracts // [])[] | select(.change == "new") | .signature + "\t" + (.kind // "?")' "$SPEC_JSON")"
  if [ -n "$NEW_CONTRACTS" ]; then
    FIRST_PATH="$(jq -r '(.change_manifest // [])[0].path // "?"' "$SPEC_JSON")"
    SECTION="## Recently Shipped (auto-generated)"
    {
      if ! grep -qF "$SECTION" "$CODE_INDEX"; then
        echo ""
        echo "$SECTION"
        echo ""
        echo "> Appended by \`scripts/spec-archive.sh\` at archive time — newly shipped public contracts."
        echo "> Fold rows into the matching domain section on the next index refresh."
        echo ""
        echo "| Capability | Entry point | Notes |"
        echo "|---|---|---|"
      fi
      while IFS="$(printf '\t')" read -r sig kind; do
        [ -n "$sig" ] || continue
        printf '| %s (%s) | `%s` | shipped %s · spec %s (auto) |\n' "$sig" "$kind" "$FIRST_PATH" "$DATE" "$SLUG"
      done <<EOF_CONTRACTS
$NEW_CONTRACTS
EOF_CONTRACTS
    } >> "$CODE_INDEX"
  fi
fi

echo "Archived '$SLUG' into baseline '$AREA':"
echo "  $BASE_JSON"
echo "  $BASE_MD"
echo "  $AUDIT (+1 record)"
if [ -f "$CODE_INDEX" ]; then
  echo "  $CODE_INDEX (capability index updated for new public contracts)"
fi
